import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import { chromium } from 'playwright';
import { createApp } from '../../server/app.js';

test('library filters, editable classification, favorites, imports and placement persist through browser/server restart', { timeout: 120_000 }, async t => {
  const dataDir = await mkdtemp(path.join(os.tmpdir(), 'tabletop-library-'));
  let server, browser;
  const stop = async () => { if (server) { await new Promise(resolve => server.close(resolve)); server = null; } };
  t.after(async () => { await browser?.close(); await stop(); await rm(dataDir, { recursive: true, force: true }); });
  const listen = async (port = 0) => {
    server = (await createApp({ dataDir })).listen(port, '127.0.0.1'); await once(server, 'listening'); return server.address().port;
  };
  const port = await listen(), origin = `http://127.0.0.1:${port}/?diagnostics`;
  browser = await chromium.launch({ executablePath: process.env.TABLETOP_BROWSER_PATH || chromium.executablePath(), headless: true, args: ['--no-sandbox', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
  const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(origin); await page.waitForFunction(() => window.__tabletop);
  await page.locator('#quick-form button[type="submit"]').click();
  await page.locator('[data-action="accept-proposal"]').click();
  await page.locator('[data-tab="assets"]').click();
  assert.equal(await page.locator('[data-asset]').count(), 24);
  await page.locator('[data-library-more]').click(); assert.equal(await page.locator('[data-asset]').count(), 48);
  while (await page.locator('[data-library-more]').isVisible()) await page.locator('[data-library-more]').click();
  const catalog = await (await page.request.get(`http://127.0.0.1:${port}/api/tabletop/assets`)).json();
  assert.equal(await page.locator('[data-asset]').count(), catalog.length);
  assert.equal(await page.locator('[data-asset="builtin-rowboat"]').count(), 1);
  await page.getByLabel('Categoria de assets', { exact: true }).selectOption('Veículos');
  assert.ok(await page.locator('[data-asset]').count() >= 6);
  await page.getByLabel('Buscar assets', { exact: true }).fill('motocicleta');
  await page.locator('[data-asset="builtin-motorcycle"]').click();
  const vehiclePoint = await page.evaluate(() => window.__tabletop.project([-1.5, 0, 0]));
  await page.mouse.click(vehiclePoint.x, vehiclePoint.y);
  await page.waitForFunction(() => Object.values(window.__tabletop.snapshot().layout.entities).some(e => e.assetRef?.id === 'builtin-motorcycle'));
  await page.locator('[data-tab=assets]').click();
  await page.locator('[data-library-clear]').click();
  await page.getByLabel('Categoria de assets', { exact: true }).selectOption('Saúde');
  await page.getByLabel('Cenário dos assets', { exact: true }).selectOption('Hospital');
  await page.getByLabel('Época dos assets', { exact: true }).selectOption('Contemporânea');
  await page.getByLabel('Filtrar por tag', { exact: true }).selectOption('sangue');
  const medicalCards = page.locator('[data-asset]');
  assert.ok(await medicalCards.count() >= 2);
  const matchedIds = await medicalCards.evaluateAll(nodes => nodes.map(node => node.dataset.asset));
  const medicalAssets = await page.evaluate(async () => (await fetch('/api/tabletop/assets')).json());
  const expectedIds = medicalAssets.filter(asset => asset.category.startsWith('Saúde / ') && asset.contexts.includes('Hospital') && asset.era === 'Contemporânea' && asset.tags.includes('sangue')).map(asset => asset.id);
  assert.deepEqual(matchedIds, expectedIds);
  await page.getByLabel('Buscar assets', { exact: true }).fill('maca');
  assert.equal(await page.locator('[data-asset]').count(), 1);
  await page.getByLabel('Editar tags de Maca hospitalar', { exact: true }).click();
  await page.getByLabel('Tags do asset', { exact: true }).fill('sangue, medicina, minha campanha, abandonado');
  await page.getByLabel('Favorito', { exact: true }).check();
  await page.getByRole('button', { name: 'Salvar classificação', exact: true }).click();
  await page.waitForFunction(() => !document.getElementById('asset-metadata-dialog').open);
  await page.locator('[data-library-clear]').click();
  await page.getByLabel('Somente favoritos', { exact: true }).check();
  assert.equal(await page.locator('[data-asset]').count(), 1);
  await page.getByLabel('Filtrar por tag', { exact: true }).selectOption('minha campanha');
  await page.getByLabel('Filtrar por tag', { exact: true }).selectOption('abandonado');
  await page.locator('[data-tab="scene"]').click(); await page.locator('[data-tab="assets"]').click();
  assert.equal(await page.locator('[data-asset]').count(), 1);
  assert.equal(await page.locator('#asset-active-tags button').count(), 2);
  await page.locator('[data-asset="builtin-gurney"]').click();
  const point = await page.evaluate(() => window.__tabletop.project([0, 0, 0]));
  await page.mouse.click(point.x, point.y);
  await page.waitForFunction(() => Object.values(window.__tabletop.snapshot().layout.entities).some(e => e.assetRef?.id === 'builtin-gurney'));
  await page.locator('#save-scene').click();
  await page.waitForFunction(() => window.__tabletop.snapshot().revision === 1);
  const saved = await page.evaluate(() => window.__tabletop.snapshot());
  await mkdir('test-results', { recursive: true });
  await page.screenshot({ path: 'test-results/asset-library.png' });
  await page.goto('about:blank'); await stop(); await listen(port); await page.goto(origin);
  await page.waitForFunction(id => window.__tabletop?.snapshot().id === id, saved.id);
  assert.deepEqual((await page.evaluate(() => window.__tabletop.snapshot())).layout, saved.layout);
  await page.locator('[data-tab="assets"]').click();
  await page.getByLabel('Somente favoritos', { exact: true }).check();
  assert.equal(await page.locator('[data-asset]').count(), 1);
  await page.getByLabel('Filtrar por tag', { exact: true }).selectOption('minha campanha');
  assert.equal(await page.locator('[data-asset="builtin-gurney"]').count(), 1);
  await page.locator('[data-library-clear]').click();
  const editorTab = await page.locator('.tabs [aria-pressed="true"]').getAttribute('data-tab');
  await page.locator('#asset-file').setInputFiles({ name: 'Retrato.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=', 'base64') });
  await page.waitForFunction(() => document.getElementById('gesture-hint').textContent.includes('Clique no piso'));
  assert.equal(await page.locator(`[data-tab="${editorTab}"]`).getAttribute('aria-pressed'), 'true', 'asset import preserves the underlying editor panel');
  await page.getByLabel('Buscar assets', { exact: true }).fill('Retrato.png');
  await page.getByLabel('Editar tags de Retrato.png', { exact: true }).click();
  await page.getByLabel('Tags do asset', { exact: true }).fill('npc, minha campanha');
  await page.getByLabel('Categoria do asset', { exact: true }).fill('Personagens / Retratos');
  await page.getByRole('button', { name: 'Salvar classificação', exact: true }).click();
  await page.waitForFunction(() => !document.getElementById('asset-metadata-dialog').open);
  await page.reload(); await page.waitForFunction(() => window.__tabletop);
  await page.locator('[data-tab="assets"]').click();
  await page.getByLabel('Categoria de assets', { exact: true }).selectOption('Personagens');
  await page.getByLabel('Filtrar por tag', { exact: true }).selectOption('minha campanha');
  assert.equal(await page.locator('[data-asset]').count(), 1);
  assert.equal(await page.locator('[data-asset] > span').textContent(), 'Retrato.png');
  // Editing the last item in a category retains the visible active filter.
  await page.getByLabel('Editar tags de Retrato.png', { exact: true }).click();
  await page.getByLabel('Categoria do asset', { exact: true }).fill('NPCs / Retratos');
  await page.getByRole('button', { name: 'Salvar classificação', exact: true }).click();
  await page.waitForFunction(() => !document.getElementById('asset-metadata-dialog').open);
  assert.equal(await page.getByLabel('Categoria de assets', { exact: true }).inputValue(), 'Personagens');
  assert.equal(await page.locator('[data-asset]').count(), 0);
  await page.locator('[data-library-clear]').click();
  await page.getByLabel('Categoria de assets', { exact: true }).selectOption('NPCs');
  assert.equal(await page.locator('[data-asset]').count(), 1);
  assert.deepEqual(errors, []);
});
