import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir,readFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {once} from 'node:events';
import express from 'express';
import {chromium} from 'playwright';
import {createApp} from '../../server/app.js';
import {reveal} from './controls.js';

for(const mode of ['server','pages'])test(`complete church gallery, roof, light history, persistence and independent projector (${mode})`,{timeout:360_000},async t=>{
  const original=JSON.parse(await readFile('public/scenes/igreja-antiga.json','utf8')),count=Object.keys(original.layout.entities).length;
  const directory=await mkdtemp(path.join(os.tmpdir(),'tabletop-full-church-')),app=mode==='server'?await createApp({dataDir:directory}):express();
  if(mode==='pages')app.use('/Tabletop',express.static(path.resolve('dist-pages')));
  const server=app.listen(0,'127.0.0.1');await once(server,'listening');
  const browser=await chromium.launch({executablePath:process.env.TABLETOP_BROWSER_PATH||chromium.executablePath(),headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  t.after(async()=>{await browser.close();await new Promise(r=>server.close(r));await rm(directory,{recursive:true,force:true});});
  const page=await browser.newPage({viewport:{width:1200,height:800},reducedMotion:'reduce'}),errors=[],requests=[];
  page.setDefaultTimeout(60_000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());page.on('request',r=>requests.push(r.url()));
  page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
  await page.goto(`http://127.0.0.1:${server.address().port}${mode==='pages'?'/Tabletop/':'/'}?diagnostics`);await page.waitForFunction(()=>!!window.__tabletop);
  const action=async name=>(await reveal(page.locator(`[data-action="${name}"]`).first())).click(),snapshot=()=>page.evaluate(()=>window.__tabletop.snapshot());
  await action('open');await page.locator('[data-open-example="igreja-antiga"] img').scrollIntoViewIfNeeded();
  if(mode==='pages'){await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>{const b=document.querySelector('[data-open-example="igreja-antiga"]').getBoundingClientRect();return b.left>=0&&b.right<=innerWidth;});const bounds=await page.locator('[data-open-example="igreja-antiga"]').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=390);await page.setViewportSize({width:1200,height:800});}
  await page.waitForFunction(()=>{const img=document.querySelector('[data-open-example="igreja-antiga"] img');return img?.complete&&img.naturalWidth===480;});
  console.log(`${mode}: capa conferida`);
  await page.locator('[data-open-example="igreja-antiga"]').click();await page.waitForFunction(n=>Object.keys(window.__tabletop.snapshot().layout.entities).length===n,count);
  const draft=await snapshot();assert.notEqual(draft.id,original.id);assert.equal(draft.revision,0);assert.ok(await page.locator('#save-status').evaluate(e=>e.classList.contains('unsaved')));
  const rockIds=Object.values(draft.layout.entities).filter(e=>e.rockShape).map(e=>e.id);
  await page.waitForFunction(ids=>ids.every(id=>window.__tabletop.stats().rockGeometries.some(g=>g.id===id)),rockIds);
  assert.deepEqual(await page.evaluate(()=>window.__tabletop.stats().assetDiagnostics),[]);
  console.log(`${mode}: igreja e referências carregadas`);
  await action('cutaway');await mkdir('test-results',{recursive:true});await page.locator('#viewport').screenshot({path:`test-results/church-exterior-${mode}.png`});
  await page.locator('[data-tab="scene"]').click();
  const source=Object.values(draft.layout.entities).find(e=>e.illumination),roof=Object.values(draft.layout.groups).find(g=>g.name.startsWith('11 ·'));
  await (await reveal(page.locator(`[data-select="${source.id}"]`))).click();
  const resources=await page.evaluate(()=>window.__tabletop.stats().resourceIds),intensity=await reveal(page.locator('[data-field="illumination-intensity"]'));
  await intensity.fill('91');await intensity.press('Tab');assert.equal((await snapshot()).layout.entities[source.id].illumination.intensity,91);
  assert.deepEqual(await page.evaluate(()=>window.__tabletop.stats().resourceIds),resources);
  await action('undo');assert.deepEqual((await snapshot()).layout,draft.layout);await action('redo');
  const [projector]=await Promise.all([page.waitForEvent('popup'),action('presentation-window')]);projector.setDefaultTimeout(60_000);projector.on('pageerror',e=>errors.push(e.message));
  await projector.waitForFunction(n=>window.__tabletop?.stats().objects===n,count+Object.keys(draft.look.lights).length);
  await projector.waitForFunction(ids=>ids.every(id=>window.__tabletop.stats().rockGeometries.some(g=>g.id===id)),rockIds);
  assert.deepEqual(await projector.evaluate(()=>window.__tabletop.stats().assetDiagnostics),[]);
  let camera=await projector.evaluate(()=>window.__tabletop.camera());await page.bringToFront();
  const presets=Object.values(draft.cameraPresets),version=await page.evaluate(()=>window.__tabletop.editVersion());
  await page.locator('#viewport canvas').focus();await page.keyboard.down('w');await page.waitForTimeout(150);await page.keyboard.up('w');
  assert.equal(await page.evaluate(()=>window.__tabletop.editVersion()),version);assert.deepEqual(await projector.evaluate(()=>window.__tabletop.camera()),camera);
  await (await reveal(page.locator(`[data-camera="${presets[3].id}"]`))).click();
  await projector.waitForFunction(p=>window.__tabletop.camera().position.every((v,i)=>Math.abs(v-p[i])<1e-6),presets[3].position);camera=await projector.evaluate(()=>window.__tabletop.camera());
  await mkdir('test-results',{recursive:true});await page.locator('#viewport').screenshot({path:`test-results/church-editor-${mode}.png`});
  await page.locator(`[data-group-visible="${roof.id}"]`).click();assert.equal((await snapshot()).layout.groups[roof.id].visible,false);
  await action('undo');assert.equal((await snapshot()).layout.groups[roof.id].visible,true);await action('redo');assert.deepEqual(await projector.evaluate(()=>window.__tabletop.camera()),camera);
  await (await reveal(page.locator(`[data-camera="${presets[8].id}"]`))).click();
  await page.locator('#viewport').screenshot({path:`test-results/church-plan-${mode}.png`});
  await projector.waitForFunction(()=>window.__tabletop.camera().projection==='orthographic');await projector.close();
  await action('save');await page.waitForFunction(()=>window.__tabletop.snapshot().revision===1&&!document.querySelector('#save-status').classList.contains('unsaved'));
  const saved=await snapshot();await page.reload();await page.waitForFunction(id=>window.__tabletop?.snapshot().id===id,saved.id);
  assert.deepEqual((await snapshot()).layout,saved.layout);assert.deepEqual((await snapshot()).cameraPresets,saved.cameraPresets);
  await action('open');await page.locator('[data-open-example="igreja-antiga"]').click();await page.waitForFunction(id=>window.__tabletop.snapshot().id!==id,saved.id);
  const second=await snapshot();assert.equal(second.revision,0);assert.equal(Object.values(second.layout.groups).find(g=>g.name.startsWith('11 ·')).visible,true);
  assert.equal(Object.values(second.layout.entities).find(e=>e.illumination).illumination.intensity,source.illumination.intensity);
  if(mode==='pages')assert.equal(requests.some(url=>url.includes('/api/')),false);assert.deepEqual(errors,[]);
  console.log(`${mode}: histórico, cobertura, projetor independente e persistência aprovados`);
});
