import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {mkdir,mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import express from 'express';
import {chromium} from 'playwright';
import {createApp} from '../../server/app.js';
import {createScene,createEntity} from '../../src/domain/documents.js';
import {LOCAL_EFFECT_DEFAULTS} from '../../src/domain/materials.js';
import {reveal} from './controls.js';

const launch=()=>chromium.launch({executablePath:process.env.TABLETOP_BROWSER_PATH||chromium.executablePath(),headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
test('dynamic lighting pixels: simultaneous zones, projections, shadow budget, scattering, AO, reflections and disposal',{timeout:150000},async t=>{
  const app=express();app.get('/',(_req,res)=>res.type('html').send('<link rel="icon" href="data:,"><style>body{margin:0;background:#222;color:white;font:16px sans-serif}#sheet{display:grid;grid-template-columns:repeat(3,400px)}figure{margin:0}img{width:400px;height:300px}figcaption{padding:8px}</style><div id="sheet"></div><script type="importmap">{"imports":{"three":"/three/build/three.module.js","three/addons/":"/three/examples/jsm/"}}</script>'));
  app.use('/three',express.static(path.resolve('node_modules/three')));app.use('/src',express.static(path.resolve('src')));const server=app.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>new Promise(r=>server.close(r)));
  const browser=await launch();t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1200,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto(`http://127.0.0.1:${server.address().port}`);
  const result=await page.evaluate(async()=>{
    const THREE=await import('three'),{createLightManager}=await import('/src/render/light-manager.js'),{createLightingZones}=await import('/src/render/lighting-zones.js'),{createEffectsPipeline}=await import('/src/render/effects.js'),{createReflectionEnvironment}=await import('/src/render/reflections.js'),{disposeObject}=await import('/src/render/asset-cache.js'),{ZONE_DEFAULTS}=await import('/src/domain/dynamic-lighting.js'),{VOLUME_DEFAULTS}=await import('/src/domain/lighting.js');
    const renderer=new THREE.WebGLRenderer({antialias:false,preserveDrawingBuffer:true});renderer.setSize(512,384);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.type=THREE.PCFShadowMap;
    const scene=new THREE.Scene();scene.background=new THREE.Color('#22222f');const camera=new THREE.OrthographicCamera(-8,8,6,-6,.1,100);camera.position.set(8,11,13);camera.lookAt(0,0,0);camera.updateMatrixWorld();const ambient=new THREE.AmbientLight('#ffffff',.8);scene.add(ambient);
    const floor=new THREE.Mesh(new THREE.PlaneGeometry(12,12).rotateX(-Math.PI/2),new THREE.MeshStandardMaterial({color:'#b6b6b6',roughness:.8}));floor.receiveShadow=true;scene.add(floor);
    renderer.render(scene,camera);const baseline={...renderer.info.memory};
    const manager=createLightManager(scene),zones=createLightingZones(),effects=createEffectsPipeline(renderer,scene),reflections=createReflectionEnvironment(renderer,scene);effects.resize(512,384);
    const host=new THREE.Group();host.position.x=-3;scene.add(host);const record={id:'room',lightingZone:{...ZONE_DEFAULTS,position:[0,2,0],size:[6,8,12],blend:.2,color:'#ff1010',intensity:.8}},doc={layout:{entities:{room:record}}},objects=new Map([['room',host]]);let look={fill:{skyColor:'#8b91b0',groundColor:'#514033',intensity:.8},rendering:{}},descriptors=[];
    const render=()=>{scene.updateMatrixWorld(true);camera.updateMatrixWorld();manager.update(descriptors,camera,new THREE.Vector3());if(manager.needsShadowUpdate())renderer.shadowMap.needsUpdate=true;effects.setLighting(zones,manager.volumeLights(),manager.quality);effects.render(camera,0);const pixels=new Uint8Array(512*384*4),gl=renderer.getContext();gl.readPixels(0,0,512,384,gl.RGBA,gl.UNSIGNED_BYTE,pixels);return {pixels,image:renderer.domElement.toDataURL()};};
    const difference=(a,b)=>{let n=0;for(let i=0;i<a.length;i+=4)if(Math.max(...[0,1,2].map(c=>Math.abs(a[i+c]-b[i+c])))>3)n++;return n;};
    const colorAt=(frame,point)=>{const p=new THREE.Vector3(...point).project(camera),x=Math.round((p.x+1)*256),y=Math.round((p.y+1)*192);return [...frame.pixels.slice((y*512+x)*4,(y*512+x)*4+3)];};
    const add=(name,frame)=>{const f=document.createElement('figure'),img=document.createElement('img'),caption=document.createElement('figcaption');img.src=frame.image;caption.textContent=name;f.append(img,caption);document.getElementById('sheet').append(f);};
    const plain=render();add('Preenchimento global',plain);zones.update(doc,objects);zones.apply(floor);const zoned=render();add('Interior vermelho + exterior neutro',zoned);
    const inside=colorAt(zoned,[-3,0,0]),outside=colorAt(zoned,[3,0,0]),outsideBefore=colorAt(plain,[3,0,0]);
    const regionalBefore=render();record.lightingZone.fogDensity=.25;zones.update(doc,objects);effects.configure(look);const regionalFog=render();add('Névoa restrita ao interior',regionalFog);const regionFogDifference=difference(regionalBefore.pixels,regionalFog.pixels),regionFogOutside=colorAt(regionalFog,[3,0,0]),regionFogOutsideBefore=colorAt(regionalBefore,[3,0,0]);
    zones.update(null,objects);const wrapper=new THREE.Group();wrapper.position.set(0,5,0);scene.add(wrapper);const source=new THREE.SpotLight('#ffffff',180,12,Math.PI/3,.1);const lightRecord={type:'spot',distance:12,angle:Math.PI/3,penumbra:.1,priority:10,shadowEnabled:true,shadowPolicy:'priority',projection:'none'};descriptors=[{id:'window',wrapper,source,record:lightRecord}];const unprojected=render();lightRecord.projection='stained';const stained=render();add('Projeção de vitral',stained);const cookieDifference=difference(unprojected.pixels,stained.pixels);
    lightRecord.projection='bars';const bars=render();add('Projeção de grades',bars);
    const blocker=new THREE.Mesh(new THREE.BoxGeometry(2,1,2),new THREE.MeshStandardMaterial({color:'#80715e'}));blocker.position.set(0,1.5,0);blocker.castShadow=true;scene.add(blocker);manager.invalidate();const blocked=render();add('Projeção ocluída',blocked);const shadowDifference=difference(bars.pixels,blocked.pixels);blocker.castShadow=false;manager.invalidate();const noCaster=render();const occlusionDifference=difference(blocked.pixels,noCaster.pixels);blocker.castShadow=true;manager.invalidate();render();
    manager.setQuality('custom',{locals:4,shadowViews:0,mapSize:512});const fallback=render(),fallbackInfo=manager.info();manager.setQuality('balanced');render();
    record.lightingZone={...ZONE_DEFAULTS,position:[0,8,0],size:[100,30,100],blend:0,fogDensity:0};zones.update(doc,objects);look={...look,volumetricFog:{...VOLUME_DEFAULTS,enabled:true,color:'#77778c',density:0,height:6,maxDistance:40}};effects.configure(look);const clearBaseline=render();look.volumetricFog.density=.07;effects.configure(look);const clearZone=render(),clearZoneDifference=difference(clearBaseline.pixels,clearZone.pixels);add('Região sem névoa dentro da névoa global',clearZone);zones.update(null,objects);
    effects.configure(look);const fog=render(),fog2=render(),fog3=render();add('Névoa sem espalhamento',fog);look.rendering.volumetricLights=true;look.rendering.volumeStrength=.8;effects.configure(look);const scattering=render();add('Névoa iluminada com sombra spot',scattering);look.rendering.volumeStrength=0;effects.configure(look);const zeroScatter=render();add('Névoa · espalhamento zero',zeroScatter);const scatteringDifference=difference(fog.pixels,scattering.pixels);
    look.volumetricFog.enabled=false;look.rendering.volumetricLights=false;effects.configure(look);const withoutAO=render();look.rendering.ao=true;look.rendering.aoIntensity=.5;effects.configure(look);const ao=render();add('Contatos com AO',ao);const aoDifference=difference(withoutAO.pixels,ao.pixels);
    const metal=new THREE.Mesh(new THREE.SphereGeometry(1,24,12),new THREE.MeshStandardMaterial({color:'#aaaaaa',metalness:1,roughness:.15}));metal.position.set(3,1,0);scene.add(metal);const noReflection=render();look.rendering.reflections=true;look.rendering.reflectionIntensity=.6;reflections.configure(look);const reflection=render();add('Reflexos de ambiente',reflection);const reflectionDifference=difference(noReflection.pixels,reflection.pixels);
    const programs=renderer.info.programs.length;effects.dispose();reflections.dispose();manager.dispose();for(const o of [host,wrapper,blocker,metal])disposeObject(o);zones.update(null,objects);renderer.render(scene,camera);const end={...renderer.info.memory};disposeObject(floor);renderer.dispose();
    return {clearZoneDifference,regionFogDifference,regionFogOutside,regionFogOutsideBefore,occlusionDifference,fog2Pixel:colorAt(fog2,[0,0,0]),fog3Pixel:colorAt(fog3,[0,0,0]),fogStable:difference(fog.pixels,fog2.pixels),zeroScatterDifference:difference(fog.pixels,zeroScatter.pixels),zeroScatterPixel:colorAt(zeroScatter,[0,0,0]),fogPixel:colorAt(fog,[0,0,0]),scatterPixel:colorAt(scattering,[0,0,0]),inside,outside,outsideBefore,cookieDifference,barsDifference:difference(stained.pixels,bars.pixels),shadowDifference,fallbackInfo,scatteringDifference,aoDifference,reflectionDifference,baseline,end,programs};
  });
  const repository=await page.evaluate(async()=>{
    const {createLightPresetRepository}=await import('/src/data/light-presets.js'),{illuminationDefaults}=await import('/src/domain/dynamic-lighting.js'),a=createLightPresetRepository({databaseName:'lighting-revisions-test'}),b=createLightPresetRepository({databaseName:'lighting-revisions-test'}),settings=illuminationDefaults('lamp');
    const pending=a.save({name:'Teste compartilhado',settings});settings.intensity=999;const first=await pending;const second=await b.save({name:'Renomeado',settings:first.settings},first);let conflict=false,duplicate=false,invalid=false;
    try{await a.remove(first);}catch{conflict=true;}
    try{await a.save({name:'RENOMEADO',settings:first.settings});}catch{duplicate=true;}
    try{await a.save({name:'Inválido',settings:{...first.settings,intensity:Infinity}});}catch{invalid=true;}
    const entries=await a.list();await a.remove(second);return {snapshot:first.settings.intensity,revision:second.revision,conflict,duplicate,invalid,count:entries.length,remaining:(await a.list()).length};
  });assert.deepEqual(repository,{snapshot:70,revision:2,conflict:true,duplicate:true,invalid:true,count:1,remaining:0});
  await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/dynamic-lighting-sheet.png',fullPage:true});console.log(JSON.stringify(result));assert.deepEqual(errors,[]);
  assert.ok(result.inside[0]>result.inside[1]*1.5,JSON.stringify(result));assert.deepEqual(result.outside,result.outsideBefore);
  for(const key of ['regionFogDifference','cookieDifference','barsDifference','shadowDifference','occlusionDifference','scatteringDifference','aoDifference','reflectionDifference'])assert.ok(result[key]>100,`${key}: ${JSON.stringify(result)}`);
  assert.deepEqual(result.regionFogOutside,result.regionFogOutsideBefore);assert.equal(result.clearZoneDifference,0);assert.equal(result.fogStable,0);assert.equal(result.zeroScatterDifference,0);assert.notDeepEqual(result.scatterPixel,result.zeroScatterPixel);assert.equal(result.fallbackInfo.shadowViews,0);assert.equal(result.fallbackInfo.projectionTextures,0);assert.deepEqual(result.end,result.baseline);
});

for(const mode of ['server','pages'])test(`lighting authoring: profiles, library, preview, zones, history, persistence and independent projector (${mode})`,{timeout:240000},async t=>{
  const dataDir=await mkdtemp(path.join(os.tmpdir(),'tabletop-lighting-'));let server,browser;t.after(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));await rm(dataDir,{recursive:true,force:true});});
  if(mode==='server')server=(await createApp({dataDir})).listen(0,'127.0.0.1');else{const app=express();app.use('/Tabletop',express.static(path.resolve('dist-pages')));server=app.listen(0,'127.0.0.1');}
  await once(server,'listening');browser=await launch();const page=await browser.newPage({viewport:{width:1600,height:1000},reducedMotion:'reduce'}),errors=[];page.setDefaultTimeout(30000);page.on('pageerror',e=>{errors.push(e.message);console.error(mode,e.message);});page.on('console',m=>{if(m.type()==='error'){errors.push(m.text());console.error(mode,m.text());}});page.on('dialog',d=>d.accept());
  await page.goto(`http://127.0.0.1:${server.address().port}${mode==='pages'?'/Tabletop/':'/'}?diagnostics`);await page.waitForFunction(()=>!!window.__tabletop);
  const scene=createScene('Iluminação reutilizável'),candle=createEntity('prop',{name:'Candelabro',assetRef:{id:'builtin-ritual-candelabra',revision:1},position:[-2,0,0]}),floor=createEntity('floor',{name:'Sala',width:12,length:10}),secret=createEntity('prop',{name:'Fonte privada',audience:'gm',position:[3,0,0],assetRef:{id:'builtin-campfire',revision:1},localEffect:structuredClone(LOCAL_EFFECT_DEFAULTS)});for(const e of [candle,floor,secret])scene.layout.entities[e.id]=e;
  await page.locator('#document-json-file').setInputFiles({name:'lighting.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(scene))});await page.waitForFunction(id=>window.__tabletop.snapshot().id===id,scene.id);
  const action=async name=>(await reveal(page.locator(`[data-action="${name}"]`).first())).click();
  const select=async id=>{if(await page.locator('[data-action="sidebar-toggle"]').getAttribute('aria-expanded')==='false')await action('sidebar-toggle');await page.locator('[data-tab="scene"]').click();await(await reveal(page.locator(`[data-select="${id}"]`))).click();};
  const option=async(field,value)=>{await(await reveal(page.locator(`[data-field="${field}"]`))).selectOption(value);};
  const number=async(field,value)=>{const input=await reveal(page.locator(`[data-field="${field}"]`));await input.fill(String(value));await input.press('Tab');};
  const check=async(field,value=true)=>{await(await reveal(page.locator(`[data-field="${field}"]`))).setChecked(value);};
  const entity=async id=>page.evaluate(id=>window.__tabletop.snapshot().layout.entities[id],id);
  await select(candle.id);await option('illumination-profile','candle');await page.waitForFunction(id=>window.__tabletop.stats().lighting.sources.includes(id+':source'),candle.id);
  const identity=await page.evaluate(id=>window.__tabletop.stats().resourceIds.find(o=>o.id===id).uuid,candle.id);await number('illumination-intensity',31);assert.equal((await entity(candle.id)).illumination.intensity,31);assert.equal(await page.evaluate(id=>window.__tabletop.stats().resourceIds.find(o=>o.id===id).uuid,candle.id),identity);
  await option('illumination-profile','torch');assert.equal((await entity(candle.id)).illumination.intensity,31);await check('illumination-pin-intensity',false);await action('illumination-recalculate');assert.equal((await entity(candle.id)).illumination.intensity,55);
  await number('illumination-position-1',1.5);await option('illumination-emissionSlot','base');await number('illumination-intensity',42);await action('illumination-copy');
  const name=await reveal(page.locator('[data-field="light-preset-name"]'));await name.fill('Luz âmbar pessoal');await action('light-preset-save');await page.waitForFunction(()=>!!document.querySelector('[data-field="light-preset-selected"]')?.value);const savedPreset=await page.locator('[data-field="light-preset-selected"]').inputValue();
  const rename=await reveal(page.locator('[data-field="light-preset-name"]'));await rename.fill('Minha fonte reutilizável');await action('light-preset-rename');await page.waitForFunction(()=>document.querySelector('[data-field="light-preset-selected"]')?.selectedOptions[0]?.textContent==='Minha fonte reutilizável');
  const [projector]=await Promise.all([page.waitForEvent('popup'),action('presentation-window')]);projector.setDefaultTimeout(30000);projector.on('pageerror',e=>errors.push(e.message));await projector.waitForFunction(id=>window.__tabletop?.stats().lighting.sources.includes(id+':source'),candle.id);const camera=await projector.evaluate(()=>window.__tabletop.camera());await page.bringToFront();
  const version=await page.evaluate(()=>window.__tabletop.editVersion());await action('illumination-preview');await page.waitForFunction(id=>!window.__tabletop.stats().lighting.sources.includes(id+':source'),candle.id);assert.equal(await page.evaluate(()=>window.__tabletop.editVersion()),version);assert.equal(await projector.evaluate(id=>window.__tabletop.stats().lighting.sources.includes(id+':source'),candle.id),true);await action('environment-preview-cancel');
  await select(floor.id);await action('illumination-paste');assert.deepEqual((await entity(floor.id)).illumination,(await entity(candle.id)).illumination);await action('undo');assert.equal((await entity(floor.id)).illumination,undefined);await action('redo');await option('illumination-profile','none');
  await option('light-preset-selected',savedPreset);await action('light-preset-preview');assert.equal((await entity(floor.id)).illumination,null);await action('environment-preview-accept');assert.equal((await entity(floor.id)).illumination.intensity,42);await action('undo');assert.equal((await entity(floor.id)).illumination,null);await action('redo');
  await action('illumination-origin-pick');const origin=await page.evaluate(()=>window.__tabletop.project([2,0,2]));await page.mouse.click(origin.x,origin.y);await page.waitForFunction(id=>Math.abs(window.__tabletop.snapshot().layout.entities[id].illumination.position[0]-2)<.05,floor.id);
  await check('zone-enabled');await number('zone-intensity',.18);await number('zone-fogDensity',.025);await check('rendering-ao');await check('rendering-reflections');await check('rendering-volumetricLights');await check('rendering-cutawayShadows');await option('lighting-quality','high');
  await page.waitForFunction(()=>window.__tabletop.stats().lighting.tier==='high'&&window.__tabletop.stats().zones===1&&window.__tabletop.stats().effects.ao);
  await projector.locator('#presentation-quality').selectOption('economy');await projector.waitForFunction(()=>window.__tabletop.stats().lighting.tier==='economy');assert.equal(await page.evaluate(()=>window.__tabletop.stats().lighting.tier),'high');
  await select(secret.id);await option('illumination-profile','ritual');await check('illumination-enabled',false);await page.waitForFunction(id=>!window.__tabletop.stats().lighting.sources.includes(id+':fire')&&!window.__tabletop.stats().lighting.sources.includes(id+':source'),secret.id);await check('illumination-enabled');await page.waitForFunction(id=>window.__tabletop.stats().lighting.sources.includes(id+':source'),secret.id);assert.equal(await projector.evaluate(id=>window.__tabletop.stats().resourceIds.find(o=>o.id===id),secret.id),undefined);assert.equal(await projector.evaluate(id=>window.__tabletop.stats().lighting.sources.includes(id+':source'),secret.id),false);
  await projector.waitForFunction(()=>window.__tabletop.stats().zones===1);assert.deepEqual(await projector.evaluate(()=>window.__tabletop.camera()),camera);await projector.close();
  await action('save');await page.waitForFunction(()=>!document.querySelector('#save-status').classList.contains('unsaved')&&!document.querySelector('[data-action="save"]').disabled);const saved=await page.evaluate(()=>window.__tabletop.snapshot());await page.reload();await page.waitForFunction(id=>window.__tabletop?.snapshot().id===id,scene.id);assert.deepEqual(await page.evaluate(()=>window.__tabletop.snapshot().layout),saved.layout);
  await select(candle.id);await page.waitForFunction(id=>!!document.querySelector(`[data-field="light-preset-selected"] option[value="${id}"]`),savedPreset);await option('light-preset-selected',savedPreset);await action('light-preset-delete');await page.waitForFunction(id=>!document.querySelector(`[data-field="light-preset-selected"] option[value="${id}"]`),savedPreset);
  await(await reveal(page.locator('[data-field="illumination-intensity"]'))).scrollIntoViewIfNeeded();await mkdir('test-results',{recursive:true});await page.screenshot({path:`test-results/dynamic-lighting-${mode}.png`});await page.setViewportSize({width:430,height:900});await select(candle.id);await(await reveal(page.locator('[data-field="illumination-intensity"]'))).scrollIntoViewIfNeeded();assert.equal(await page.locator('[data-texture-options="illumination-library"]').evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);await page.screenshot({path:`test-results/dynamic-lighting-${mode}-mobile.png`});assert.deepEqual(errors,[]);
});
