import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, mkdir } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import { chromium } from 'playwright';
import express from 'express';
import { createApp } from '../../server/app.js';
import { createScene, createEntity, createLight } from '../../src/domain/documents.js';
import { primaryLight } from '../../src/domain/environments.js';
import { reveal } from './controls.js';

test('day/night, named materials, weather, previews and saved environments work through the UI and survive restart', {timeout:240_000}, async t => {
  const dataDir=await mkdtemp(path.join(os.tmpdir(),'tabletop-environments-'));
  let server,browser,page; const errors=[];
  t.after(async()=>{ await browser?.close(); if(server) await new Promise(resolve=>server.close(resolve)); await rm(dataDir,{recursive:true,force:true}); });
  async function listen() { server=(await createApp({dataDir})).listen(0,'127.0.0.1');await once(server,'listening'); }
  const origin=()=>`http://127.0.0.1:${server.address().port}`;
  async function launch() {
    browser=await chromium.launch({executablePath:process.env.TABLETOP_BROWSER_PATH||chromium.executablePath(),headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
    page=await browser.newPage({viewport:{width:1600,height:1000}});page.setDefaultTimeout(30_000);
    page.on('dialog',dialog=>dialog.accept(dialog.type()==='prompt'?'Noite chuvosa':undefined));
    page.on('pageerror',error=>errors.push(error.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});
    await page.goto(`${origin()}/?diagnostics`); await page.waitForFunction(()=>!!window.__tabletop);
  }
  const action=async name=>(await reveal(page.locator(`[data-action="${name}"]`).first())).click();
  const field=async(name,value)=>{const node=await reveal(page.locator(`[data-field="${name}"]`));await node.fill(String(value));await node.press('Tab');};
  const check=async(name,value=true)=>(await reveal(page.locator(`[data-field="${name}"]`))).setChecked(value);
  const select=async(name,value)=>(await reveal(page.locator(`[data-field="${name}"]`))).selectOption(value);
  const snapshot=()=>page.evaluate(()=>window.__tabletop.snapshot());
  const stats=()=>page.evaluate(()=>window.__tabletop.stats());
  const render=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  await listen();
  const scene=createScene('Rua de investigação'), floor=createEntity('floor',{width:12,length:12}), wall=createEntity('wall',{length:8,position:[-4,0,-3]}), glass=createEntity('window',{wallId:wall.id,offset:4,sill:1,width:2,height:1.2,style:'glass'});
  const prop=createEntity('prop',{name:'Objeto que reage ao horário',position:[1,0,0],assetRef:{id:'builtin-wardrobe',revision:1}}), other=createEntity('prop',{name:'Outra instância',position:[-2,0,0],assetRef:{id:'builtin-wardrobe',revision:1}});
  for(const entity of [floor,wall,glass,prop,other])scene.layout.entities[entity.id]=entity;
  const light=createLight({name:'Poste noturno',position:[0,3,0],intensity:30});scene.look.lights[light.id]=light;
  const created=await fetch(`${origin()}/api/tabletop/scenes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document:scene})});assert.equal(created.status,201);
  await launch();await action('open');await page.locator(`[data-open="${scene.id}"]`).click();await page.waitForFunction(id=>window.__tabletop.snapshot().id===id,scene.id);
  await page.locator('[data-tab="scene"]').click();
  await page.locator('[data-environment="warm"]').click();await check('effects-paused');await render();
  assert.equal((await snapshot()).look.daylight.phase,'sunset');assert.equal((await stats()).atmosphere.sky,true);
  await mkdir('test-results',{recursive:true});
  const afternoon=await page.locator('#viewport canvas').screenshot({path:'test-results/environment-afternoon.png'});
  await page.locator('[data-environment="moonlight"]').click();await check('effects-paused');await render();
  const night=await page.locator('#viewport canvas').screenshot({path:'test-results/environment-night.png'});assert.notDeepEqual(afternoon,night);
  await page.waitForFunction(id=>window.__tabletop.stats().environmentMaterials.some(m=>m.id===id && m.color==='#ffc86d'),glass.id);
  await field('scene-key-intensity',.8);await field('scene-key-temperature',11000);assert.equal(primaryLight((await snapshot()).look).temperature,11000);
  await field('scene-key-hue',120);await field('scene-key-saturation',65);assert.equal(primaryLight((await snapshot()).look).temperature,null);
  await field('scene-key-altitude',35);await field('scene-key-azimuth',50);await field('daylight-exposure',1.3);
  assert.equal(Number(await page.locator('[data-field="scene-key-altitude"]').inputValue()),35);
  const beforeSky = await snapshot(); await action('environment-view-sky'); await render();
  const skyCamera = await page.evaluate(()=>window.__tabletop.camera()); assert.ok(skyCamera.target[1]>skyCamera.position[1]); assert.deepEqual(await snapshot(),beforeSky);
  await page.locator('#viewport canvas').screenshot({path:'test-results/environment-night-sky.png'}); await action('environment-return-map');
  assert.ok((await page.evaluate(()=>window.__tabletop.camera())).position[1]>0);
  await page.locator(`[data-select="${prop.id}"]`).click();await reveal(page.locator('[data-field="binding-slot"]'));
  const slots=await page.locator('[data-field="binding-slot"] option').evaluateAll(nodes=>nodes.map(n=>n.value));assert.ok(slots.includes('wood'));
  await select('binding-slot','wood');await check('binding-enabled');await field('binding-color','#ffbb44');await field('binding-intensity',2.5);
  await page.waitForFunction(id=>window.__tabletop.stats().environmentMaterials.some(m=>m.id===id && m.slot==='wood' && m.intensity===2.5),prop.id);
  assert.ok(!(await stats()).environmentMaterials.some(m=>m.id===other.id && m.color==='#ffbb44'),'other asset instance is unchanged');
  assert.ok((await stats()).environmentMaterials.filter(m=>m.id===prop.id && m.color==='#ffbb44').every(m=>m.slot==='wood'));
  await page.locator(`[data-select="${light.id}"]`).click();await check('binding-enabled');
  await page.locator('[data-environment="day"]').click();await page.waitForFunction(id=>window.__tabletop.stats().lights.find(l=>l.id===id)?.intensity===0,light.id);
  assert.ok(!(await stats()).environmentMaterials.some(m=>m.id===glass.id));
  await page.locator('[data-environment="moonlight"]').click();await page.waitForFunction(id=>window.__tabletop.stats().lights.find(l=>l.id===id)?.intensity===30,light.id);
  await select('weather-type','rain');await field('weather-count',200);await field('weather-center-1',1);await field('weather-size-1',8);await field('weather-seed',42);
  await page.waitForFunction(()=>window.__tabletop.stats().atmosphere.particles===200 && window.__tabletop.stats().animatedAtmosphere);
  const before=await snapshot(), version=await page.evaluate(()=>window.__tabletop.editVersion()), time=(await stats()).effectTime;
  await page.waitForFunction(value=>window.__tabletop.stats().effectTime>value+.08,time);assert.deepEqual(await snapshot(),before);assert.equal(await page.evaluate(()=>window.__tabletop.editVersion()),version);
  await check('effects-paused');const paused=(await stats()).effectTime;await page.waitForTimeout(150);assert.equal((await stats()).effectTime,paused);
  await check('effects-paused',false);await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>!window.__tabletop.stats().animatedAtmosphere);await page.emulateMedia({reducedMotion:'no-preference'});
  const original=await snapshot(), camera=await page.evaluate(()=>window.__tabletop.camera());
  await page.locator('[data-environment-preview="swamp"]').click();assert.deepEqual(await snapshot(),original);assert.equal((await stats()).atmosphere.weather,'dust');
  await action('environment-preview-cancel');assert.deepEqual(await snapshot(),original);assert.equal((await stats()).atmosphere.weather,'rain');assert.deepEqual(await page.evaluate(()=>window.__tabletop.camera()),camera);
  await action('environment-save');await page.waitForFunction(()=>document.querySelector('[data-field="environment-library"]').options.length===2);
  const presetId=await page.locator('[data-field="environment-library"]').inputValue();assert.ok(presetId);
  const exportedPreset=await (await fetch(`${origin()}/api/tabletop/environments/${presetId}`)).json(), beforeImport=await snapshot();
  await page.locator('#document-json-file').setInputFiles({name:'preset.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exportedPreset))});
  await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Ambientes são presets'));assert.deepEqual(await snapshot(),beforeImport);
  const [projector]=await Promise.all([page.waitForEvent('popup'),action('presentation-window')]);await projector.waitForFunction(()=>window.__tabletop?.stats().atmosphere.weather==='rain');
  const published=await projector.evaluate(()=>window.__tabletop.camera());
  await page.bringToFront();await page.locator('[data-environment-preview="heat"]').click();assert.equal(await projector.evaluate(()=>window.__tabletop.stats().atmosphere.weather),'rain','preview is local');
  await action('environment-preview-accept');await projector.waitForFunction(()=>window.__tabletop.stats().atmosphere.weather==='dust');assert.deepEqual(await projector.evaluate(()=>window.__tabletop.camera()),published);
  await action('environment-custom-apply');await page.waitForFunction(()=>window.__tabletop.snapshot().look.weather.type==='rain');assert.equal((await snapshot()).look.weather.type,'rain');
  await projector.locator('#presentation-effects').click();assert.equal(await projector.evaluate(()=>window.__tabletop.stats().atmosphere.particles),0);assert.equal((await stats()).atmosphere.particles,200);
  await page.bringToFront();await check('viewport-effects',false);assert.equal((await stats()).atmosphere.particles,0);await check('viewport-effects');
  await check('effects-paused');await select('weather-type','smoke');await render();assert.equal((await stats()).atmosphere.weather,'smoke');await select('weather-type','embers');await render();assert.equal((await stats()).atmosphere.weather,'embers');
  await action('environment-custom-apply');await page.waitForFunction(()=>window.__tabletop.snapshot().look.weather.type==='rain');await action('save');await page.waitForFunction(()=>!document.querySelector('#save-status').classList.contains('unsaved'));
  const saved=await snapshot();await browser.close();browser=null;await new Promise(resolve=>server.close(resolve));server=null;
  await listen();await launch();await action('open');await page.locator(`[data-open="${saved.id}"]`).click();await page.waitForFunction(id=>window.__tabletop.snapshot().id===id,saved.id);
  assert.deepEqual((await snapshot()).look,saved.look);await page.locator('[data-tab="scene"]').click();await select('environment-library',presetId);
  await page.locator('[data-environment="day"]').click();await action('environment-custom-preview');await page.waitForSelector('[data-action="environment-preview-accept"]');assert.equal((await stats()).atmosphere.phase,'night');assert.equal((await snapshot()).look.daylight.phase,'day');await action('environment-preview-accept');assert.equal((await snapshot()).look.daylight.phase,'night');
  await action('environment-delete');await page.waitForFunction(()=>document.querySelector('[data-field="environment-library"]').options.length===1);assert.equal((await snapshot()).look.daylight.phase,'night');
  assert.deepEqual(errors,[]);
});


test('procedural sky draws sun/moon above the horizon, clouds move and seeded rain changes actual GPU pixels', {timeout:60_000}, async t => {
  const app=express();
  app.get('/',(_req,res)=>res.type('html').send('<link rel="icon" href="data:,"><script type="importmap">{"imports":{"three":"/three/build/three.module.js","three/addons/":"/three/examples/jsm/"}}</script>'));
  app.use('/three',express.static(path.resolve('node_modules/three')));app.use('/src',express.static(path.resolve('src')));
  const server=app.listen(0,'127.0.0.1');await once(server,'listening');let browser;
  t.after(async()=>{await browser?.close();await new Promise(resolve=>server.close(resolve));});
  browser=await chromium.launch({executablePath:process.env.TABLETOP_BROWSER_PATH||chromium.executablePath(),headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  const page=await browser.newPage(), errors=[];page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  const result=await page.evaluate(async()=>{
    const THREE=await import('three'), {createAtmosphere}=await import('/src/render/atmosphere.js'), {SKY_DEFAULTS,WEATHER_DEFAULTS}=await import('/src/domain/lighting.js');
    const renderer=new THREE.WebGLRenderer({antialias:false,preserveDrawingBuffer:true});renderer.setSize(96,96);renderer.setPixelRatio(1);renderer.toneMapping=THREE.ACESFilmicToneMapping;
    const scene=new THREE.Scene();scene.background=new THREE.Color('#000000');const runtime=createAtmosphere(scene);
    const camera=new THREE.PerspectiveCamera(60,1,.1,1200);camera.position.set(0,2,0);camera.lookAt(0,12,10);
    const light={color:'#ffe8b0',rotation:new THREE.Quaternion().setFromEuler(new THREE.Euler(Math.PI/4,0,0)).toArray()};
    const look={sky:{...SKY_DEFAULTS,enabled:true,clouds:false,stars:false,discSize:.07},daylight:{phase:'day'},weather:{...WEATHER_DEFAULTS}};
    const gl=renderer.getContext();
    const read=(seconds)=>{runtime.update(camera,seconds,false,96);renderer.render(scene,camera);const bytes=new Uint8Array(96*96*4);gl.readPixels(0,0,96,96,gl.RGBA,gl.UNSIGNED_BYTE,bytes);return [...bytes];};
    const center=bytes=>bytes.slice((48*96+48)*4,(48*96+48)*4+3);
    runtime.configure(look,light);const sun=read(0);look.sky.celestialEnabled=false;runtime.configure(look,light);const noSun=read(0);
    look.sky.celestialEnabled=true;look.daylight.phase='night';look.sky.topColor='#071329';look.sky.horizonColor='#304f84';runtime.configure(look,light);const moon=read(0);
    look.sky.celestialEnabled=false;look.sky.clouds=true;look.sky.cloudCoverage=.6;look.sky.cloudOpacity=.9;look.sky.cloudSpeed=.2;runtime.configure(look,light);const cloudsA=read(0),cloudsB=read(8);
    look.sky.enabled=false;look.weather={...WEATHER_DEFAULTS,type:'rain',count:350,center:[0,0,3],size:[8,8,8],color:'#ffffff',opacity:1};camera.lookAt(0,3,10);runtime.configure(look,light);
    const rainA=read(0),rainB=read(.35);runtime.setEnabled(false);const noRain=read(.35);
    const info=runtime.info(), geometries=renderer.info.memory.geometries;
    for(let i=0;i<8;i++){runtime.configure(look,light);read(.35);}
    const stable=renderer.info.memory.geometries<=geometries+1;runtime.dispose();renderer.dispose();renderer.forceContextLoss();
    return {sun:center(sun),noSun:center(noSun),moon:center(moon),cloudsChanged:cloudsA.some((v,i)=>v!==cloudsB[i]),rainChanged:rainA.some((v,i)=>v!==rainB[i]),rainVisible:rainB.some((v,i)=>i%4!==3&&v>0),noRainBlack:noRain.every((v,i)=>i%4===3||v===0),info,stable};
  });
  assert.ok(result.sun[0]>result.noSun[0]+50,JSON.stringify(result));assert.ok(result.moon.every(v=>v>100),JSON.stringify(result));
  assert.equal(result.cloudsChanged,true);assert.equal(result.rainChanged,true);assert.equal(result.rainVisible,true);assert.equal(result.noRainBlack,true);assert.equal(result.info.particles,0);assert.equal(result.stable,true);assert.deepEqual(errors,[]);
});
