import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, mkdir } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import { chromium } from 'playwright';
import express from 'express';
import { createApp } from '../../server/app.js';
import { reveal } from './controls.js';

test('advanced lights and atmosphere render, pause, project independently and survive a full restart', { timeout: 180_000 }, async t => {
  const dataDir = await mkdtemp(path.join(os.tmpdir(), 'tabletop-lighting-'));
  let server, browser;
  const errors = [];
  t.after(async () => { await browser?.close(); if (server) await new Promise(resolve => server.close(resolve)); await rm(dataDir, { recursive: true, force: true }); });
  async function launch() {
    server = (await createApp({ dataDir })).listen(0, '127.0.0.1'); await once(server, 'listening');
    browser = await chromium.launch({ executablePath: process.env.TABLETOP_BROWSER_PATH || chromium.executablePath(), headless: true, args: ['--no-sandbox', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
    const page = await browser.newPage({ viewport: { width: 1500, height: 950 } });
    page.setDefaultTimeout(30_000);
    page.on('dialog', dialog => dialog.accept());
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
    await page.goto(`http://127.0.0.1:${server.address().port}/?diagnostics`);
    await page.waitForFunction(() => !!window.__tabletop); return page;
  }
  let page = await launch();
  const action = async name => (await reveal(page.locator(`[data-action="${name}"]`).first())).click();
  const field = async (name, value) => { const input = await reveal(page.locator(`[data-field="${name}"]`)); await input.fill(String(value)); await input.press('Tab'); };
  const check = async (name, value = true) => (await reveal(page.locator(`[data-field="${name}"]`))).setChecked(value);
  const snapshot = () => page.evaluate(() => window.__tabletop.snapshot());
  const stats = () => page.evaluate(() => window.__tabletop.stats());
  const rendered = () => page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  await action('floor-add');
  await action('spot-place');
  const point = await page.evaluate(() => window.__tabletop.project([0, 0, 0]));
  await page.mouse.click(point.x, point.y);
  await page.waitForSelector('[data-field="light-angle"]');
  const lightId = Object.values((await snapshot()).look.lights).find(l => l.type === 'spot').id;
  await field('light-angle', 70); await field('light-penumbra', .6);
  await field('light-pitch', 35); await field('object-yaw', 60);
  const rotated = (await snapshot()).look.lights[lightId].rotation;
  const pitchHalf = 35 * Math.PI / 360, yawHalf = 60 * Math.PI / 360;
  const expectedRotation = [Math.cos(yawHalf) * Math.sin(pitchHalf), Math.sin(yawHalf) * Math.cos(pitchHalf), -Math.sin(yawHalf) * Math.sin(pitchHalf), Math.cos(yawHalf) * Math.cos(pitchHalf)];
  assert.ok(rotated.every((v, i) => Math.abs(v - expectedRotation[i]) < 1e-7), 'numeric yaw preserves the edited tilt');
  assert.equal(Number(await page.locator('[data-field="object-yaw"]').inputValue()), 60);
  await check('light-shadow');
  await check('light-useTemperature'); await field('light-temperature', 2800);
  await check('flicker-enabled'); await field('flicker-amplitude', .45); await field('flicker-seed', 42);
  await page.waitForFunction(() => window.__tabletop.stats().animatedLights);
  const documentBeforeAnimation = await snapshot(), version = await page.evaluate(() => window.__tabletop.editVersion());
  const intensityBefore = (await stats()).lights.find(l => l.type === 'spot').intensity;
  await page.waitForFunction(({ lightId, intensity }) => window.__tabletop.stats().lights.find(l => l.id === lightId)?.intensity !== intensity, { lightId, intensity: intensityBefore });
  assert.equal(await page.evaluate(() => window.__tabletop.editVersion()), version);
  assert.deepEqual(await snapshot(), documentBeforeAnimation);

  await page.locator('[data-tab="scene"]').click();
  await check('effects-paused'); await page.waitForFunction(() => !window.__tabletop.stats().animatedLights);
  const paused = (await stats()).lights.find(l => l.type === 'spot').intensity;
  await page.waitForTimeout(160); assert.equal((await stats()).lights.find(l => l.type === 'spot').intensity, paused);
  await check('effects-paused', false);
  await page.emulateMedia({ reducedMotion: 'reduce' }); await page.waitForFunction(() => !window.__tabletop.stats().animatedLights);
  await page.emulateMedia({ reducedMotion: 'no-preference' }); await page.waitForFunction(() => window.__tabletop.stats().animatedLights);
  await check('effects-paused');
  await check('fog-enabled'); await page.waitForFunction(() => window.__tabletop.stats().fog === 'linear');
  await (await reveal(page.locator('[data-field="fog-mode"]'))).selectOption('exp2');
  await field('fog-density', .04);
  await page.waitForFunction(() => window.__tabletop.stats().fog === 'exp2');
  await check('volume-enabled'); await field('volume-height', 5); await field('volume-density', .15);
  await check('bloom-enabled'); await field('bloom-threshold', .5);
  await page.waitForFunction(() => window.__tabletop.stats().effects.bloom && window.__tabletop.stats().effects.volumetricFog);
  await mkdir('test-results', { recursive: true });
  await rendered();
  const withEffects = await page.locator('#viewport canvas').screenshot({ path: 'test-results/advanced-lighting.png' });
  const fullLook = (await snapshot()).look;
  await check('viewport-effects', false); await rendered();
  const withoutEffects = await page.locator('#viewport canvas').screenshot();
  assert.notDeepEqual(withEffects, withoutEffects, 'volume/bloom affect rendered pixels');
  assert.deepEqual((await snapshot()).look, fullLook, 'local quality does not edit the scene');
  assert.equal((await stats()).effects.bloom, false);
  assert.equal((await stats()).fog, null, 'local effects also remove distance fog without editing the look');
  await check('viewport-effects'); await rendered();
  assert.equal((await stats()).fog, 'exp2');
  const resourceCount = (await stats()).textures;
  for (let i = 0; i < 3; i++) { await check('viewport-effects', false); await rendered(); await check('viewport-effects'); await rendered(); }
  assert.ok((await stats()).textures <= resourceCount + 2, 'switching effects releases old targets');

  const published = await page.evaluate(() => window.__tabletop.camera());
  const [projector] = await Promise.all([page.waitForEvent('popup'), action('presentation-window')]);
  projector.on('pageerror', error => errors.push(error.message));
  projector.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
  await projector.waitForFunction(() => window.__tabletop?.stats().effects.volumetricFog);
  await projector.locator('#presentation-effects').click();
  assert.equal(await projector.evaluate(() => window.__tabletop.stats().effects.bloom), false);
  assert.equal((await stats()).effects.bloom, true, 'projector quality is independent');
  await page.bringToFront();
  await field('volume-density', .12);
  assert.deepEqual(await projector.evaluate(() => window.__tabletop.camera()), published, 'look edits do not publish a new camera');
  await page.locator('#scene-name').fill('Luzes e névoa'); await page.locator('#scene-name').press('Tab');
  await action('save'); await page.waitForFunction(() => window.__tabletop.snapshot().revision > 0);
  const saved = await snapshot();
  await browser.close(); browser = null; await new Promise(resolve => server.close(resolve)); server = null;
  page = await launch();
  await action('open');
  await page.locator(`[data-open="${saved.id}"]`).click();
  await page.waitForFunction(id => window.__tabletop.snapshot().id === id, saved.id);
  assert.deepEqual((await snapshot()).look, saved.look);
  assert.deepEqual((await snapshot()).look.lights[lightId].rotation, saved.look.lights[lightId].rotation);
  await page.waitForFunction(() => window.__tabletop.stats().effects.bloom && window.__tabletop.stats().fog === 'exp2');
  assert.deepEqual(errors, []);
});

test('height fog stops at opaque depth in both cameras; bloom affects only highlights above its threshold', { timeout: 60_000 }, async t => {
  // A small native-module fixture tests actual GPU output without editing a document.
  const app = express();
  app.get('/', (_req, res) => res.type('html').send('<link rel="icon" href="data:,"><script type="importmap">{"imports":{"three":"/three/build/three.module.js","three/addons/":"/three/examples/jsm/"}}</script>'));
  app.use('/three', express.static(path.resolve('node_modules/three')));
  app.get('/effects.js', (_req, res) => res.sendFile(path.resolve('src/render/effects.js')));
  const server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
  let browser;
  t.after(async () => { await browser?.close(); await new Promise(resolve => server.close(resolve)); });
  browser = await chromium.launch({ executablePath: process.env.TABLETOP_BROWSER_PATH || chromium.executablePath(), headless: true, args: ['--no-sandbox', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
  const page = await browser.newPage(), errors = [];
  page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  const result = await page.evaluate(async () => {
    const THREE = await import('three'), { createEffectsPipeline } = await import('/effects.js');
    const renderer = new THREE.WebGLRenderer({ antialias: false, preserveDrawingBuffer: true });
    renderer.setSize(64, 64); renderer.setPixelRatio(1);
    renderer.outputColorSpace = THREE.LinearSRGBColorSpace; renderer.toneMapping = THREE.NoToneMapping;
    const scene = new THREE.Scene(); scene.background = new THREE.Color(0, 0, 0);
    const surface = new THREE.Mesh(new THREE.PlaneGeometry(20, 20), new THREE.MeshBasicMaterial({ color: '#000000' })); scene.add(surface);
    const pipeline = createEffectsPipeline(renderer, scene); pipeline.resize(64, 64);
    const gl = renderer.getContext();
    const camera = new THREE.PerspectiveCamera(60, 1, .1, 100); camera.position.set(0, 0, 5); camera.lookAt(0, 0, 0);
    const read = (camera, x = 32) => { pipeline.render(camera, 0); const rgba = new Uint8Array(4); gl.readPixels(x, 32, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, rgba); return rgba[0]; };
    const volume = { enabled: true, color: '#ffffff', density: .1, baseHeight: -1, height: 2, maxDistance: 80 };
    pipeline.configure({ volumetricFog: volume }); const perspective = read(camera);
    const ortho = new THREE.OrthographicCamera(-3, 3, 3, -3, .1, 100); ortho.position.copy(camera.position); ortho.lookAt(0, 0, 0);
    const orthographic = read(ortho);
    surface.visible = false; const background = read(camera); surface.visible = true;
    pipeline.configure({ volumetricFog: { ...volume, baseHeight: 2 } }); const outside = read(camera);
    pipeline.configure({ volumetricFog: { ...volume, maxDistance: 1 } }); const limited = read(camera);
    pipeline.configure({}); const clear = read(camera);
    surface.geometry.dispose(); surface.geometry = new THREE.PlaneGeometry(.5, .5); surface.material.color.setRGB(5, 5, 5);
    const noBloom = read(camera, 38);
    pipeline.configure({ bloom: { enabled: true, strength: .8, radius: .3, threshold: 1 } }); const bloom = read(camera, 38);
    pipeline.configure({ bloom: { enabled: true, strength: .8, radius: .3, threshold: 10 } }); const belowThreshold = read(camera, 38);
    pipeline.dispose(); surface.geometry.dispose(); surface.material.dispose(); renderer.dispose(); renderer.forceContextLoss();
    return { perspective, orthographic, background, outside, limited, clear, noBloom, bloom, belowThreshold };
  });
  assert.ok(result.perspective >= 96 && result.perspective <= 102, JSON.stringify(result));
  assert.ok(Math.abs(result.perspective - result.orthographic) <= 2, JSON.stringify(result));
  assert.ok(result.background > 250, 'no geometry means a longer path through the fog');
  assert.equal(result.outside, 0); assert.equal(result.clear, 0);
  assert.ok(result.limited >= 22 && result.limited <= 26);
  assert.equal(result.noBloom, 0); assert.ok(result.bloom > 0); assert.equal(result.belowThreshold, 0);
  assert.deepEqual(errors, []);
});
