import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, mkdir } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import express from 'express';
import { chromium } from 'playwright';
import { createApp } from '../../server/app.js';
import { createScene, createEntity } from '../../src/domain/documents.js';
import { LOCAL_EFFECT_DEFAULTS } from '../../src/domain/materials.js';
import { reveal } from './controls.js';

const launch=()=>chromium.launch({executablePath:process.env.TABLETOP_BROWSER_PATH||chromium.executablePath(),headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});

test('textured materials, terrain layers and local fire/smoke render through UI, survive restart and keep projector camera independent',{timeout:240_000},async t=>{
  const dataDir=await mkdtemp(path.join(os.tmpdir(),'tabletop-materials-'));let server,browser,page;const errors=[];
  t.after(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));await rm(dataDir,{recursive:true,force:true});});
  async function listen(){server=(await createApp({dataDir})).listen(0,'127.0.0.1');await once(server,'listening');}
  const origin=()=>`http://127.0.0.1:${server.address().port}`;
  async function open(){browser=await launch();page=await browser.newPage({viewport:{width:1600,height:1000}});page.setDefaultTimeout(25_000);page.on('dialog',dialog=>dialog.accept());page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto(`${origin()}/?diagnostics`);await page.waitForFunction(()=>!!window.__tabletop);}
  const action=async name=>(await reveal(page.locator(`[data-action="${name}"]`).first())).click();
  const select=async(name,value)=>(await reveal(page.locator(`[data-field="${name}"]`).first())).selectOption(value);
  const field=async(name,value)=>{const node=await reveal(page.locator(`[data-field="${name}"]`).first());await node.fill(String(value));await node.press('Tab');};
  const check=async(name,value=true)=>(await reveal(page.locator(`[data-field="${name}"]`).first())).setChecked(value);
  const snapshot=()=>page.evaluate(()=>window.__tabletop.snapshot());
  const stats=()=>page.evaluate(()=>window.__tabletop.stats());
  await listen();
  const scene=createScene('Materiais e fogueiras'),floor=createEntity('floor',{width:8,length:8}),prop=createEntity('prop',{assetRef:{id:'builtin-wardrobe',revision:1},position:[2,0,0]}),terrain=createEntity('terrain',{position:[-10,0,0],width:8,length:8,segments:8});
  for(const entity of [floor,prop,terrain])scene.layout.entities[entity.id]=entity;
  assert.equal((await fetch(`${origin()}/api/tabletop/scenes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document:scene})})).status,201);
  await open();await action('open');await page.locator(`[data-open="${scene.id}"]`).click();await page.waitForFunction(id=>window.__tabletop.snapshot().id===id,scene.id);
  await page.locator('[data-tab="scene"]').click();await page.locator(`[data-select="${floor.id}"]`).click();
  await select('material-texture','wood');await field('material-textureSize',1.5);await field('material-relief',.05);
  await page.waitForFunction(id=>window.__tabletop.stats().surfaceMaterials.some(m=>m.id===id && m.texture==='wood' && m.size===1.5),floor.id);
  await action('undo');assert.equal((await snapshot()).layout.entities[floor.id].material.relief,.035);await action('redo');
  await field('material-woodBoards',9);await select('material-woodDirection','vertical');await field('material-woodGap',6);await field('material-woodGrain',.8);
  await field('material-textureColor','#42755b');await field('material-textureBrightness',.6);await field('material-textureRotation',30);
  const custom=(await snapshot()).layout.entities[floor.id].material;assert.equal(custom.textureColorMode,'replace');assert.equal(custom.woodGap,.06);assert.equal(custom.woodBoards,9);
  await action('undo');assert.equal((await snapshot()).layout.entities[floor.id].material.textureRotation,0);await action('redo');
  await page.waitForFunction(id=>window.__tabletop.stats().surfaceMaterials.some(m=>m.id===id&&m.options.woodBoards===9&&m.options.textureBrightness===.6),floor.id);
  await page.locator(`[data-select="${prop.id}"]`).click();await page.waitForFunction(()=>document.querySelector('[data-field="material-textureSlot"]').options.length>1);
  await select('material-textureSlot','wood');await select('material-texture','wood');
  const materials=(await stats()).surfaceMaterials.filter(m=>m.id===prop.id);assert.ok(materials.length);assert.ok(materials.every(m=>m.slot==='wood'));
  await select('material-texture','metal');await select('material-metalPattern','diamond');await field('material-metalWear',40);
  assert.equal((await snapshot()).layout.entities[prop.id].material.metalWear,.4);
  await page.locator(`[data-select="${terrain.id}"]`).click();await select('terrain-layer-texture','grass');await field('terrain-layer-textureSize',.75);
  assert.equal((await snapshot()).layout.entities[terrain.id].paintLayers[0].texture,'grass');
  const mask=(await snapshot()).layout.entities[terrain.id].paintLayers[0].weights;
  await field('terrain-layer-textureColor','#447788');await field('terrain-layer-textureBrightness',.75);await field('terrain-layer-textureRotation',90);await field('terrain-layer-patternDensity',2);assert.equal(await page.locator('[data-texture-options="terrain-layer-"]').evaluate(node=>node.open),true);await field('terrain-layer-textureSeed',12);
  assert.deepEqual((await snapshot()).layout.entities[terrain.id].paintLayers[0].weights,mask);
  await page.locator(`[data-select="${floor.id}"]`).click();
  await page.locator('[data-tab="build"]').click();await action('fire-place');
  let point=await page.evaluate(()=>window.__tabletop.project([0,0,0]));await page.mouse.click(point.x,point.y);
  await page.waitForSelector('[data-field="effect-type"]');const fire=Object.values((await snapshot()).layout.entities).find(e=>e.localEffect?.type==='fire');assert.ok(fire);
  await field('effect-size-1',2);await field('effect-lightIntensity',35);await field('effect-count',64);
  await page.waitForFunction(()=>window.__tabletop.stats().animatedLocalEffects);
  const stable=await snapshot(),version=await page.evaluate(()=>window.__tabletop.editVersion()),clock=(await stats()).effectTime;
  await page.waitForFunction(time=>window.__tabletop.stats().effectTime>time+.1,clock);assert.deepEqual(await snapshot(),stable);assert.equal(await page.evaluate(()=>window.__tabletop.editVersion()),version);
  await action('object-duplicate');assert.equal(Object.values((await snapshot()).layout.entities).filter(e=>e.localEffect?.type==='fire').length,2);await action('undo');
  await action('smoke-place');point=await page.evaluate(()=>window.__tabletop.project([-2,0,0]));await page.mouse.click(point.x,point.y);await page.waitForSelector('[data-field="effect-type"]');
  assert.equal(Object.values((await snapshot()).layout.entities).filter(e=>e.localEffect?.type==='smoke').length,1);
  await page.locator('[data-tab="scene"]').click();await check('effects-paused');await page.waitForFunction(()=>!window.__tabletop.stats().animatedLocalEffects);
  const paused=(await stats()).effectTime;await page.waitForTimeout(120);assert.equal((await stats()).effectTime,paused);
  await mkdir('test-results',{recursive:true});await page.locator('#viewport canvas').screenshot({path:'test-results/materials-fire-smoke.png'});
  const [projector]=await Promise.all([page.waitForEvent('popup'),action('presentation-window')]);projector.on('pageerror',e=>errors.push(e.message));await projector.waitForFunction(()=>window.__tabletop?.stats().localEffects.length===2);
  const camera=await projector.evaluate(()=>window.__tabletop.camera());
  await page.bringToFront();await page.locator(`[data-select="${floor.id}"]`).click();await select('material-texture','stone');await projector.waitForFunction(id=>window.__tabletop.stats().surfaceMaterials.some(m=>m.id===id&&m.texture==='stone'),floor.id);assert.deepEqual(await projector.evaluate(()=>window.__tabletop.camera()),camera);
  const textureCount=(await stats()).textures;
  for(const id of ['sand','metal','brick','concrete','wood']) await select('material-texture',id);
  assert.ok((await stats()).textures<=textureCount+2,'atlas resources stay bounded while switching');
  for(const boards of [7,11,16,8]) await field('material-woodBoards',boards);
  await select('material-woodPattern','parquet');await select('material-woodDirection','vertical');await field('material-textureColor','#855b36');await field('material-textureBrightness',.7);
  await projector.waitForFunction(id=>window.__tabletop.stats().surfaceMaterials.some(m=>m.id===id&&m.options.woodBoards===8&&m.options.woodPattern==='parquet'&&m.options.textureBrightness===.7),floor.id);
  assert.deepEqual(await projector.evaluate(()=>window.__tabletop.camera()),camera);assert.ok((await stats()).textures<=textureCount+2,'changing patterns releases previous variant atlases');
  await page.locator('#viewport canvas').screenshot({path:'test-results/custom-materials.png'});
  await check('viewport-effects',false);await page.waitForFunction(()=>window.__tabletop.stats().localEffects.every(e=>e.count===0));assert.ok((await projector.evaluate(()=>window.__tabletop.stats())).localEffects.some(e=>e.count>0));await check('viewport-effects');
  await check('effects-paused',false);await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>!window.__tabletop.stats().animatedLocalEffects);await page.emulateMedia({reducedMotion:'no-preference'});await check('effects-paused');
  await action('save');await page.waitForFunction(()=>!document.querySelector('#save-status').classList.contains('unsaved'));const saved=await snapshot();
  await browser.close();browser=null;await new Promise(r=>server.close(r));server=null;await listen();await open();await action('open');await page.locator(`[data-open="${scene.id}"]`).click();await page.waitForFunction(id=>window.__tabletop.snapshot().id===id,scene.id);
  assert.deepEqual((await snapshot()).layout,saved.layout);await page.waitForFunction(()=>window.__tabletop.stats().localEffects.length===2);assert.deepEqual(errors,[]);
});

test('all surface presets change real GPU pixels; terrain blends masks and local effects animate without shader errors',{timeout:90_000},async t=>{
  const app=express();app.get('/',(_req,res)=>res.type('html').send('<link rel="icon" href="data:,"><script type="importmap">{"imports":{"three":"/three/build/three.module.js","three/addons/":"/three/examples/jsm/"}}</script>'));
  app.use('/three',express.static(path.resolve('node_modules/three')));app.use('/src',express.static(path.resolve('src')));
  const server=app.listen(0,'127.0.0.1');await once(server,'listening');const browser=await launch(),page=await browser.newPage();const errors=[];
  t.after(async()=>{await browser.close();await new Promise(r=>server.close(r));});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto(`http://127.0.0.1:${server.address().port}`);
  const result=await page.evaluate(async()=>{
    const THREE=await import('three'),{createSurfaceLibrary,applySurfaceTextures}=await import('/src/render/surface-materials.js'),{createEntity}=await import('/src/domain/documents.js'),{createFloor,createTerrain}=await import('/src/render/scene-objects.js'),{SURFACE_MATERIALS,surfacePatch,LOCAL_EFFECT_DEFAULTS,smokeDefaults}=await import('/src/domain/materials.js'),{createLocalEffect,updateLocalEffect}=await import('/src/render/local-effects.js'),{disposeObject}=await import('/src/render/asset-cache.js');
    const renderer=new THREE.WebGLRenderer({preserveDrawingBuffer:true});renderer.setSize(240,240);renderer.outputColorSpace=THREE.SRGBColorSpace;document.body.append(renderer.domElement);
    const scene=new THREE.Scene();scene.background=new THREE.Color('#222222');scene.add(new THREE.HemisphereLight('#ffffff','#888888',3));const light=new THREE.DirectionalLight('#ffffff',3);light.position.set(3,5,2);scene.add(light);
    const camera=new THREE.PerspectiveCamera(45,1,.1,100);camera.position.set(0,4,3);camera.lookAt(0,0,0);const library=createSurfaceLibrary();
    let lastChannels;const capture=()=>{renderer.render(scene,camera);const bytes=new Uint8Array(240*240*4);renderer.getContext().readPixels(0,0,240,240,renderer.getContext().RGBA,renderer.getContext().UNSIGNED_BYTE,bytes);let hash=2166136261;for(const byte of bytes) hash=Math.imul(hash^byte,16777619);lastChannels=[0,0,0];for(let i=0;i<bytes.length;i+=4)for(let c=0;c<3;c++)lastChannels[c]+=bytes[i+c]/(240*240);return hash>>>0;};
    const plain=createFloor(createEntity('floor'));scene.add(plain);capture();disposeObject(plain);const baseline=renderer.info.memory.textures;
    const hashes=[];for(const preset of SURFACE_MATERIALS){const entity=createEntity('floor',{width:4,length:4,material:surfacePatch(preset.id)}),view=createFloor(entity);applySurfaceTextures(view,entity,library);scene.add(view);hashes.push(capture());disposeObject(view);}
    const customFloor=(patch,legacy=false)=>{const entity=createEntity('floor',{width:4,length:4,material:legacy?{color:'#ffffff',roughness:.72,metalness:0,texture:'wood',textureSize:2,relief:.035}:{...surfacePatch('wood'),...patch}}),view=createFloor(entity);applySurfaceTextures(view,entity,library);scene.add(view);const hash=capture(),channels=[...lastChannels];disposeObject(view);return {hash,channels};};
    const original=customFloor({}),dark=customFloor({textureBrightness:.25}),green=customFloor({textureColor:'#208a45',textureColorMode:'replace'}),gray=customFloor({textureSaturation:0});
    const woodVariants=[{woodBoards:9},{woodDirection:'vertical'},{woodGap:.1},{woodPattern:'grain'},{woodPattern:'parquet'},{textureRotation:45},{woodGrain:0},{textureSeed:42}].map(patch=>customFloor(patch));
    const metals=['brushed','smooth','diamond','corrugated','rusted'].map(metalPattern=>customFloor({...surfacePatch('metal'),metalPattern}));
    const legacy=customFloor({},true);
    const terrain=createEntity('terrain',{width:4,length:4,segments:4});terrain.paintLayers=[{id:'grass',color:'#ffffff',opacity:1,visible:true,texture:'grass',textureSize:1,weights:Array(25).fill(1)},{id:'mud',color:'#ffffff',opacity:1,visible:true,texture:'mud',textureSize:2,weights:Array.from({length:25},(_,i)=>i%5/4)}];
    const ground=createTerrain(terrain);applySurfaceTextures(ground,terrain,library);scene.add(ground);const blend=capture();disposeObject(ground);
    terrain.paintLayers[0].textureColor='#a43a7c';terrain.paintLayers[0].textureColorMode='replace';terrain.paintLayers[0].textureRotation=45;
    terrain.paintLayers[1].textureSeed=18;terrain.paintLayers[1].patternDensity=2;
    const alteredGround=createTerrain(terrain);applySurfaceTextures(alteredGround,terrain,library);scene.add(alteredGround);const customBlend=capture();disposeObject(alteredGround);
    const fullTerrain=createEntity('terrain',{width:4,length:4,segments:4,material:{...surfacePatch('wood'),woodBoards:11}});
    fullTerrain.paintLayers=Array.from({length:8},(_,i)=>({id:`layer-${i}`,name:`Madeira ${i}`,color:'#ffffff',opacity:.25,visible:true,texture:'wood',woodBoards:i+1,textureSize:2,weights:Array(25).fill(1)}));
    const fullView=createTerrain(fullTerrain);applySurfaceTextures(fullView,fullTerrain,library);scene.add(fullView);const fullBlend=capture();disposeObject(fullView);
    fullTerrain.paintLayers[7].textureColor='#408830';fullTerrain.paintLayers[7].textureColorMode='replace';
    const fullEdited=createTerrain(fullTerrain);applySurfaceTextures(fullEdited,fullTerrain,library);scene.add(fullEdited);const fullEditedBlend=capture();disposeObject(fullEdited);
    const fire=createLocalEffect(LOCAL_EFFECT_DEFAULTS),smoke=createLocalEffect(smokeDefaults());fire.position.x=-.7;smoke.position.x=.7;scene.add(fire,smoke);camera.position.set(0,2,6);camera.lookAt(0,1,0);
    updateLocalEffect(fire,1,true,false);updateLocalEffect(smoke,1,true,false);const first=capture();updateLocalEffect(fire,1.8,true,false);updateLocalEffect(smoke,1.8,true,false);const second=capture();
    updateLocalEffect(fire,1.8,false,false);updateLocalEffect(smoke,1.8,false,false);const hidden=capture();disposeObject(fire);disposeObject(smoke);library.dispose();capture();const textures=renderer.info.memory.textures;renderer.dispose();return {hashes,blend,customBlend,fullBlend,fullEditedBlend,original,dark,green,gray,woodVariants,metals,legacy,first,second,hidden,textures,baseline};
  });
  assert.equal(new Set(result.hashes).size,8);
  assert.equal(result.original.hash,result.legacy.hash);assert.ok(result.dark.channels.reduce((a,b)=>a+b,0)<result.original.channels.reduce((a,b)=>a+b,0)*.8);
  assert.ok(Math.max(...result.gray.channels)-Math.min(...result.gray.channels)<1,'zero saturation removes the original color');assert.notEqual(result.fullBlend,result.fullEditedBlend,'the eighth custom layer changes pixels in a nine-style atlas');
  assert.ok(result.green.channels[1]>result.green.channels[0]*1.2,'recoloring produces a visibly green material');
  assert.equal(new Set([result.original.hash,...result.woodVariants.map(v=>v.hash)]).size,9);assert.equal(new Set(result.metals.map(v=>v.hash)).size,5);assert.notEqual(result.blend,result.customBlend);assert.ok(!result.hashes.includes(result.blend));assert.notEqual(result.first,result.second);assert.notEqual(result.second,result.hidden);assert.equal(result.textures,result.baseline);assert.deepEqual(errors,[]);
});
