import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {once} from 'node:events';
import {chromium} from 'playwright';
import {createApp} from '../../server/app.js';
import {createScene,createEntity} from '../../src/domain/documents.js';
import {rockDefaults} from '../../src/domain/rocks.js';
import {surfacePatch,coverageDefaults} from '../../src/domain/materials.js';
import {applyEnvironment} from '../../src/domain/environments.js';
import {reveal} from './controls.js';

test('cliff kit can be edited, reset, duplicated, saved and projected with independent cameras',{timeout:240_000},async t=>{
  const dataDir=await mkdtemp(path.join(os.tmpdir(),'tabletop-cliffs-')),server=(await createApp({dataDir})).listen(0,'127.0.0.1');await once(server,'listening');
  const browser=await chromium.launch({executablePath:process.env.TABLETOP_BROWSER_PATH||chromium.executablePath(),headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  t.after(async()=>{await browser.close();await new Promise(r=>server.close(r));await rm(dataDir,{recursive:true,force:true});});
  const page=await browser.newPage({viewport:{width:1440,height:900}}),origin=`http://127.0.0.1:${server.address().port}`,errors=[];
  page.setDefaultTimeout(30_000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('dialog',d=>d.accept());
  const scene=applyEnvironment(createScene('Trilha e paredão · kit de montanha'),'fog');scene.look.fog.density=.005;scene.layout.grid.visible=false;scene.look.volumetricFog.enabled=false;
  const floor=createEntity('floor',{name:'Trilha nevada',width:16,length:16,material:surfacePatch('snow')});scene.layout.entities[floor.id]=floor;
  const add=(id,position,material)=>{const e=createEntity('prop',{name:id,position,assetRef:{id:`builtin-${id}`,revision:1},...(rockDefaults(`builtin-${id}`)?{rockShape:rockDefaults(`builtin-${id}`)}:{}),...(material?{material}:{})});scene.layout.entities[e.id]=e;return e;};
  const cliff=add('mountain-cliff-face',[-3,0,-3],{...surfacePatch('rock'),rockPattern:'strata',coverage:{...coverageDefaults(),physicalThickness:.05}});
  add('mountain-ruin-tower',[3,.05,-2]);add('mountain-timber-platform',[2,.05,2]);add('mountain-wall-lantern',[-2.5,1,-1.3]);
  assert.equal((await fetch(`${origin}/api/tabletop/scenes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document:scene})})).status,201);
  await page.goto(`${origin}/?diagnostics`);await page.waitForFunction(()=>!!window.__tabletop);
  const action=async name=>(await reveal(page.locator(`[data-action="${name}"]`).first())).click();
  const snapshot=()=>page.evaluate(()=>window.__tabletop.snapshot());
  const field=async(name,value)=>{const n=await reveal(page.locator(`[data-field="${name}"]`).first());await n.fill(String(value));await n.press('Tab');};
  await action('open');await page.locator(`[data-open="${scene.id}"]`).click();await page.waitForFunction(id=>window.__tabletop.snapshot().id===id,scene.id);
  await page.locator('[data-tab="scene"]').click();await page.locator(`[data-select="${cliff.id}"]`).click();
  await page.waitForFunction(id=>window.__tabletop.stats().rockGeometries.some(g=>g.id===id&&g.form==='cliff'),cliff.id);
  await field('rock-overhang',.9);await field('rock-terraces',9);await field('rock-erosion',.85);await field('rock-seed',707);
  assert.deepEqual((await snapshot()).layout.entities[cliff.id].material,cliff.material);
  assert.deepEqual((await snapshot()).layout.entities[cliff.id].transform,cliff.transform);
  await action('undo');assert.equal((await snapshot()).layout.entities[cliff.id].rockShape.seed,137);await action('redo');
  await action('rock-reset');assert.deepEqual((await snapshot()).layout.entities[cliff.id].rockShape,rockDefaults('builtin-mountain-cliff-face'));await action('undo');
  await action('object-duplicate');assert.equal(Object.values((await snapshot()).layout.entities).filter(e=>e.rockShape?.seed===707).length,2);await action('undo');
  await page.locator(`[data-select="${floor.id}"]`).click();await action('perspective');await action('frame');await page.waitForFunction(()=>!window.__tabletop.stats().cameraMoving);
  await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/mountain-kit.png'});
  const [projector]=await Promise.all([page.waitForEvent('popup'),action('presentation-window')]);projector.on('pageerror',e=>errors.push(e.message));
  await projector.waitForFunction(id=>window.__tabletop?.stats().rockGeometries.some(g=>g.id===id&&g.terraces===9&&g.overhang===.9),cliff.id);
  const camera=await projector.evaluate(()=>window.__tabletop.camera());await page.bringToFront();await page.locator(`[data-select="${cliff.id}"]`).click();await field('rock-terraces',5);
  await projector.waitForFunction(id=>window.__tabletop.stats().rockGeometries.some(g=>g.id===id&&g.terraces===5),cliff.id);assert.deepEqual(await projector.evaluate(()=>window.__tabletop.camera()),camera);await projector.close();
  await action('save');await page.waitForFunction(()=>!document.querySelector('#save-status').classList.contains('unsaved')&&!document.querySelector('[data-action="save"]').disabled);const saved=await snapshot();
  await page.reload();await page.waitForFunction(id=>window.__tabletop?.snapshot().id===id,scene.id);assert.deepEqual((await snapshot()).layout,saved.layout);assert.deepEqual(errors,[]);
});
