import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, mkdir } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import { chromium } from 'playwright';
import { createApp } from '../../server/app.js';
import { reveal } from './controls.js';

test('scene and object disclosures retain state; libraries fade in/out and can reopen during closing', { timeout: 120_000 }, async t => {
  const dataDir = await mkdtemp(path.join(os.tmpdir(), 'tabletop-panels-'));
  const server = (await createApp({ dataDir })).listen(0, '127.0.0.1'); await once(server, 'listening');
  const browser = await chromium.launch({ executablePath: process.env.TABLETOP_BROWSER_PATH || chromium.executablePath(), headless: true, args: ['--no-sandbox', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
  t.after(async () => { await browser.close(); await new Promise(resolve => server.close(resolve)); await rm(dataDir, { recursive: true, force: true }); });
  const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } }), errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${server.address().port}/?diagnostics`); await page.waitForFunction(() => !!window.__tabletop);
  const action = async key => (await reveal(page.locator(`[data-action="${key}"]`).first())).click();
  const field = async (key, value) => { const node = await reveal(page.locator(`[data-field="${key}"]`)); await node.fill(String(value)); await node.press('Tab'); };
  const snapshot = () => page.evaluate(() => window.__tabletop.snapshot());
  await action('floor-add'); await page.locator('[data-tab=scene]').click();
  assert.deepEqual(await page.locator('.panel-group > summary strong').allTextContents(), ['Atmosfera', 'Câmera e apresentação', 'Elementos e documento']);
  const original = await snapshot(), camera = await page.evaluate(() => window.__tabletop.camera());
  const sun = page.locator('[data-panel-section=sun]'), sky = page.locator('[data-panel-section=sky]');
  await sun.locator(':scope > summary').focus(); await page.keyboard.press('Enter');
  assert.equal(await sun.evaluate(node => node.open), true);
  await field('scene-key-intensity', 1.7);
  assert.equal(await sun.evaluate(node => node.open), true); assert.equal(await sky.evaluate(node => node.open), false);
  assert.equal(await sun.locator(':scope > section').evaluate(node => node.getAnimations().length), 0, 'editing does not restart the opening fade');
  await page.locator('[data-tab=build]').click(); await page.locator('[data-tab=scene]').click();
  assert.equal(await sun.evaluate(node => node.open), true);
  const floor = Object.values((await snapshot()).layout.entities).find(entity => entity.kind === 'floor');
  await page.locator(`[data-select="${floor.id}"]`).click();
  const support = page.locator('#inspector-content > details').filter({ has: page.locator('summary', { hasText: 'Superfície de apoio' }) });
  await support.locator(':scope > summary').click(); await field('width', 7);
  assert.equal(await support.evaluate(node => node.open), true);
  await support.locator(':scope > summary').click(); await field('length', 8);
  assert.equal(await support.evaluate(node => node.open), false);
  await action('undo'); await action('undo'); await action('undo'); assert.deepEqual(await snapshot(), original);
  const version = await page.evaluate(() => window.__tabletop.editVersion());
  // Inspect the actual fade in the same event turn, before it can finish.
  const entered = await page.evaluate(() => {
    document.querySelector('[data-tab=assets]').click();
    const dialog = document.querySelector('#assets-dialog');
    return { duration: dialog.getAnimations()[0]?.effect.getTiming().duration, open: dialog.open };
  });
  assert.deepEqual(entered, { duration: 100, open: true });
  await page.waitForTimeout(120);
  const exiting = await page.evaluate(() => {
    document.querySelector('[data-action=assets-close]').click();
    const dialog = document.querySelector('#assets-dialog');
    return { open: dialog.open, inert: dialog.inert, duration: dialog.getAnimations()[0]?.effect.getTiming().duration, frames: dialog.getAnimations()[0]?.effect.getKeyframes().map(frame => frame.opacity) };
  });
  assert.equal(exiting.open, true); assert.equal(exiting.inert, true); assert.equal(exiting.duration, 80); assert.equal(exiting.frames.at(-1), '0');
  await page.locator('#assets-dialog').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('[data-tab=assets]').getAttribute('aria-expanded'), 'false');
  await page.locator('[data-tab=assets]').click();
  await page.evaluate(() => { document.querySelector('[data-action=assets-close]').click(); document.querySelector('[data-tab=assets]').click(); });
  await page.waitForTimeout(150); assert.equal(await page.locator('#assets-dialog').evaluate(node => node.open && !node.inert), true);
  await page.keyboard.press('Escape'); await page.locator('#assets-dialog').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('[data-tab=assets]').evaluate(node => node === document.activeElement), true);
  await action('open'); const documents = page.locator('#documents-dialog'); await documents.waitFor({ state: 'visible' });
  const bounds = await documents.boundingBox(); assert.ok(bounds.x >= 8 && bounds.x + bounds.width <= 1600 && bounds.y + bounds.height <= 1000);
  assert.equal(await documents.evaluate(node => getComputedStyle(node).backdropFilter), 'none');
  const documentExit = await page.evaluate(() => { document.querySelector('[data-action=close-dialog]').click(); return document.querySelector('#documents-dialog').getAnimations()[0]?.effect.getTiming().duration; });
  assert.equal(documentExit, 80); await documents.waitFor({ state: 'hidden' });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const reduced = await page.evaluate(() => {
    document.querySelector('[data-tab=assets]').click(); const dialog = document.querySelector('#assets-dialog');
    const animations = dialog.getAnimations().length; document.querySelector('[data-action=assets-close]').click();
    return { animations, open: dialog.open };
  });
  assert.deepEqual(reduced, { animations: 0, open: false });
  assert.deepEqual(await snapshot(), original); assert.equal(await page.evaluate(() => window.__tabletop.editVersion()), version);
  assert.deepEqual(await page.evaluate(() => window.__tabletop.camera()), camera);
  await mkdir('test-results', { recursive: true }); await page.screenshot({ path: 'test-results/panel-consistency.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForFunction(() => document.querySelector('.app-shell').classList.contains('sidebar-collapsed'));
  await page.locator('[data-action=sidebar-toggle]').click();
  for (const key of ['atmosphere', 'elements']) await page.locator(`[data-panel-section=${key}] > summary`).click();
  const mobileGroups = await page.locator('.panel-group').evaluateAll(nodes => nodes.map(node => {
    const rect = node.getBoundingClientRect(); return { left: rect.left, right: rect.right };
  }));
  assert.ok(mobileGroups.every(rect => rect.left >= 0 && rect.right <= 390));
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth) <= 390);
  assert.equal(await page.locator('[data-action=inspector-toggle]').getAttribute('aria-expanded'), 'false');
  assert.deepEqual(await snapshot(), original);
  await page.screenshot({ path: 'test-results/panel-consistency-mobile.png' });
  assert.deepEqual(errors, []);
});
