import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir,readFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {once} from 'node:events';
import {chromium} from 'playwright';
import * as THREE from 'three';
import {createApp} from '../../server/app.js';
import {createScene,createEntity} from '../../src/domain/documents.js';
import {rockDefaults} from '../../src/domain/rocks.js';
import {recipeInstance,disposeObject} from '../../src/render/asset-cache.js';
import {surfacePatch,coverageDefaults} from '../../src/domain/materials.js';
import {reveal} from './controls.js';

test('brush sculpts cliff faces/top and switches from ground; cancel/undo/save and projector retain manual shape',{timeout:210_000},async t=>{
  const dataDir=await mkdtemp(path.join(os.tmpdir(),'tabletop-sculpt-')),server=(await createApp({dataDir})).listen(0,'127.0.0.1');await once(server,'listening');
  const browser=await chromium.launch({executablePath:process.env.TABLETOP_BROWSER_PATH||chromium.executablePath(),headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  t.after(async()=>{await browser.close();await new Promise(r=>server.close(r));await rm(dataDir,{recursive:true,force:true});});
  const page=await browser.newPage({viewport:{width:1440,height:900}}),origin=`http://127.0.0.1:${server.address().port}`,errors=[];
  page.setDefaultTimeout(30_000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('dialog',d=>d.accept());
  const scene=createScene('Escultura livre · paredão e chão'),terrain=createEntity('terrain',{width:18,length:18,segments:16,position:[0,-.05,0]});scene.layout.grid.visible=false;scene.layout.entities[terrain.id]=terrain;
  const cliff=createEntity('prop',{name:'Paredão esculpível',assetRef:{id:'builtin-mountain-cliff-face',revision:1},rockShape:rockDefaults('builtin-mountain-cliff-face'),material:{...surfacePatch('rock'),coverage:{...coverageDefaults(),physicalThickness:.03}}});scene.layout.entities[cliff.id]=cliff;
  const {assets}=JSON.parse(await readFile('public/assets/catalog.json','utf8')),catalog=assets.find(a=>a.id===cliff.assetRef.id),recipe=JSON.parse(await readFile(`public${catalog.url}`,'utf8')),model=recipeInstance(recipe,cliff.rockShape,catalog.bounds);model.updateMatrixWorld(true);
  const face=new THREE.Raycaster(new THREE.Vector3(0,3,10),new THREE.Vector3(0,0,-1)).intersectObject(model,true)[0].point.toArray();
  const peak=new THREE.Raycaster(new THREE.Vector3(0,12,0),new THREE.Vector3(0,-1,0)).intersectObject(model,true)[0].point.toArray();disposeObject(model);
  assert.equal((await fetch(`${origin}/api/tabletop/scenes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document:scene})})).status,201);
  await page.goto(`${origin}/?diagnostics`);await page.waitForFunction(()=>!!window.__tabletop);
  const action=async name=>(await reveal(page.locator(`[data-action="${name}"]`).first())).click(),snapshot=()=>page.evaluate(()=>window.__tabletop.snapshot());
  const field=async(name,value)=>{const n=await reveal(page.locator(`[data-field="${name}"]`).first());await n.fill(String(value));await n.press('Tab');};
  const point=position=>page.evaluate(v=>window.__tabletop.project(v),position);
  const stroke=async(position,cancel=false)=>{const p=await point(position);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x+12,p.y+5,{steps:4});if(cancel)await page.keyboard.press('Escape');await page.mouse.up();};
  await action('open');await page.locator(`[data-open="${scene.id}"]`).click();await page.waitForFunction(id=>window.__tabletop.snapshot().id===id,scene.id);
  await page.locator('[data-tab="scene"]').click();await page.locator(`[data-select="${terrain.id}"]`).click();await action('perspective');await action('frame');await page.waitForFunction(()=>!window.__tabletop.stats().cameraMoving);
  await action('terrain-sculpt');await stroke(face);await page.waitForFunction(id=>!!window.__tabletop.snapshot().layout.entities[id].rockSculpt?.stamps.length,cliff.id);
  assert.deepEqual((await snapshot()).layout.entities[terrain.id].heights,terrain.heights,'hitting the cliff does not alter ground');assert.deepEqual((await snapshot()).layout.entities[cliff.id].rockShape,cliff.rockShape);
  await action('undo');assert.equal((await snapshot()).layout.entities[cliff.id].rockSculpt,undefined);await action('redo');
  await (await reveal(page.locator('[data-field="brush-mode"]'))).selectOption('push');await field('brush-strength',.6);await field('brush-radius',1.5);
  const beforeCancel=await snapshot();await stroke(face,true);assert.deepEqual((await snapshot()).layout,beforeCancel.layout);
  await action('rock-sculpt');await stroke(face);await page.waitForFunction(id=>window.__tabletop.stats().sculptedRocks.some(r=>r.id===id&&r.samples>=2),cliff.id);
  const faceStamps=(await snapshot()).layout.entities[cliff.id].rockSculpt.stamps.length;
  await (await reveal(page.locator('[data-field="brush-mode"]'))).selectOption('lower');await stroke(peak);assert.ok((await snapshot()).layout.entities[cliff.id].rockSculpt.stamps.length>faceStamps);
  const custom=structuredClone((await snapshot()).layout.entities[cliff.id].rockSculpt);await action('rock-sculpt-clear');assert.equal((await snapshot()).layout.entities[cliff.id].rockSculpt.stamps.length,0);await action('undo');assert.deepEqual((await snapshot()).layout.entities[cliff.id].rockSculpt,custom);
  await action('object-duplicate');assert.equal(Object.values((await snapshot()).layout.entities).filter(e=>e.rockSculpt?.stamps.length).length,2);await action('undo');
  await action('tool-select');await page.locator(`[data-select="${cliff.id}"]`).click();await page.locator('#viewport canvas').focus();await page.keyboard.press('f');await page.waitForFunction(()=>!window.__tabletop.stats().cameraMoving);
  await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/rock-sculpt-editor.png'});
  const [projector]=await Promise.all([page.waitForEvent('popup'),action('presentation-window')]);await projector.waitForFunction(id=>window.__tabletop?.stats().sculptedRocks.some(r=>r.id===id),cliff.id);const camera=await projector.evaluate(()=>window.__tabletop.camera());
  await page.bringToFront();await action('rock-sculpt');await stroke(face);await projector.waitForFunction(({id,count})=>window.__tabletop.stats().sculptedRocks.some(r=>r.id===id&&r.samples>count),{id:cliff.id,count:custom.stamps.length});assert.deepEqual(await projector.evaluate(()=>window.__tabletop.camera()),camera);await projector.close();
  await action('terrain-stop');await action('save');await page.waitForFunction(()=>!document.querySelector('#save-status').classList.contains('unsaved')&&!document.querySelector('[data-action="save"]').disabled);const saved=await snapshot();
  await page.reload();await page.waitForFunction(id=>window.__tabletop?.snapshot().id===id,scene.id);await page.waitForFunction(id=>window.__tabletop.stats().sculptedRocks.some(r=>r.id===id),cliff.id);assert.deepEqual((await snapshot()).layout,saved.layout);
  // T also activates on an anchored rock composition when no terrain exists.
  await page.locator('[data-tab="scene"]').click();await page.locator(`[data-select="${terrain.id}"]`).click();await action('object-delete');
  await page.locator(`[data-select="${cliff.id}"]`).click();await action('object-duplicate');await page.locator(`[data-select="${cliff.id}"]`).click({modifiers:['Shift']});await action('assembly-bind');
  const grouped=(await snapshot()).layout;assert.ok(Object.values(grouped.groups).some(g=>g.anchored));
  await page.locator('#viewport canvas').focus();await page.keyboard.press('t');assert.ok(await page.locator('[data-action="terrain-stop"]').isVisible());assert.deepEqual((await snapshot()).layout,grouped,'activating a grouped surface brush does not edit documents');await action('terrain-stop');
  assert.deepEqual(errors,[]);
});
