import { ENVIRONMENTS, primaryLight } from '../domain/environments.js';
import { SKY_DEFAULTS, WEATHER_DEFAULTS, DAYLIGHT_DEFAULTS, NIGHT_WINDOWS_DEFAULTS, BINDING_DEFAULTS, colorToHSV } from '../domain/lighting.js';
import { Euler, Quaternion } from 'three';
import { escapeHTML as esc } from './icons.js';

export function environmentPanel(doc, saved, selected, open, { numberField: n, colorField: c, checkField: b }) {
  const look = doc.look ?? doc.defaultLook, light = primaryLight(look), daylight = { ...DAYLIGHT_DEFAULTS, ...look.daylight };
  const sky = { ...SKY_DEFAULTS, ...look.sky }, weather = { ...WEATHER_DEFAULTS, ...look.weather }, windows = { ...NIGHT_WINDOWS_DEFAULTS, ...look.nightWindows };
  const hsv = colorToHSV(light?.color ?? '#ffe8c5'), angles = new Euler().setFromQuaternion(new Quaternion(...(light?.rotation ?? [0, 0, 0, 1])), 'YXZ');
  const details = (key, title, content) => `<details data-atmosphere-section="${key}" ${open.has(key) ? 'open' : ''}><summary>${title}</summary>${content}</details>`;
  return `<section><span class="eyebrow">AMBIENTES E HORÁRIOS</span><h2>Prepare a atmosfera.</h2><p class="muted">Escolha um ponto de partida e ajuste sol, lua, céu e clima aqui.</p>
    <div class="environment-options">${ENVIRONMENTS.map(p => `<div class="environment-option"><button data-environment="${p.id}" title="${esc(p.description)}" class="environment-card ${doc.sourceEnvironment?.id === p.id ? 'active' : ''}"><span class="environment-swatch ${p.id}"></span><span><strong>${esc(p.name)}</strong><small>${esc(p.description)}</small></span></button><button data-environment-preview="${p.id}" class="environment-preview" aria-label="Prévia de ${esc(p.name)}" title="Experimentar sem alterar a cena">Prévia</button></div>`).join('')}</div>
    ${details('library', 'Meus ambientes', `<label class="field"><span>Ambiente salvo</span><select data-field="environment-library"><option value="">Escolha um ambiente</option>${saved.map(p => `<option value="${p.id}" ${selected === p.id ? 'selected' : ''}>${esc(p.name)}</option>`).join('')}</select></label><div class="field-grid"><button data-action="environment-custom-apply" ${selected ? '' : 'disabled'}>Aplicar</button><button data-action="environment-custom-preview" ${selected ? '' : 'disabled'}>Prévia</button></div><button data-action="environment-save" class="wide">Salvar atmosfera como novo ambiente</button><div class="field-grid"><button data-action="environment-overwrite" ${selected ? '' : 'disabled'}>Atualizar selecionado</button><button data-action="environment-delete" class="danger" ${selected ? '' : 'disabled'}>Excluir selecionado</button></div><p class="microcopy">Salva aparência e clima no computador. Geometria, objetos, vínculos e câmeras continuam na cena.</p>`)}
  </section>
  <section><span class="eyebrow">SOL / LUA E COR DA LUZ</span>
    <label class="field"><span>Horário da cena</span><select data-field="daylight-phase">${[['day','Dia'],['sunset','Tarde'],['night','Noite']].map(([v,l]) => `<option value="${v}" ${daylight.phase === v ? 'selected' : ''}>${l}</option>`).join('')}</select></label>
    ${b('scene-key-enabled', daylight.phase === 'night' ? 'Lua ilumina a cena' : 'Sol ilumina a cena', light?.enabled !== false)}
    ${n('scene-key-intensity', daylight.phase === 'night' ? 'Intensidade da lua' : 'Intensidade do sol', light?.intensity ?? 2.2, { min: 0, step: .1 })}
    ${b('scene-key-useTemperature', 'Usar temperatura da luz', light?.temperature != null)}
    ${n('scene-key-temperature', 'Temperatura · Kelvin', light?.temperature ?? 6000, { min: 1000, max: 40000, step: 100 })}
    ${c('scene-key-color', 'Cor do sol / lua', light?.color ?? '#ffe8c5')}
    <div class="axis-fields">${n('scene-key-hue', 'Matiz · H°', hsv.hue, { min: 0, max: 360, step: 5 })}${n('scene-key-saturation', 'Saturação %', hsv.saturation * 100, { min: 0, max: 100, step: 5 })}${n('scene-key-value', 'Brilho · %', hsv.value * 100, { min: 0, max: 100, step: 5 })}</div><p class="microcopy">A intensidade controla a luz emitida. Cor e HSV permitem pintar a atmosfera; ao editá-los, Kelvin fica desligado.</p>
    ${details('sun-direction', 'Direção e sombras', `${n('scene-key-altitude', 'Altura no céu · graus', 90 - angles.x * 180 / Math.PI, { min: 1, max: 90, step: 5 })}${n('scene-key-azimuth', 'Direção horizontal · graus', angles.y * 180 / Math.PI, { min: -180, max: 180, step: 5 })}${b('scene-key-shadow', 'Sol / lua projeta sombras', light?.shadowEnabled ?? true)}<button data-action="environment-select-light" class="wide">Selecionar luz principal no inspetor</button>`)}
    ${n('daylight-exposure', 'Exposição da cena', daylight.exposure, { min: .2, max: 4 })}
    ${n('fill-intensity', 'Luz ambiente · intensidade', look.fill.intensity, { min: 0 })}${c('fill-color', 'Luz ambiente · cor', look.fill.skyColor)}${c('fill-groundColor', 'Luz refletida pelo chão', look.fill.groundColor)}
  </section>
  <section><span class="eyebrow">CÉU E NUVENS</span>${b('sky-enabled', 'Mostrar céu', sky.enabled)}<div class="field-grid"><button data-action="environment-view-sky">Enquadrar sol / lua</button><button data-action="environment-return-map">Enquadrar mapa</button></div><p class="microcopy">Olhe para o céu sem publicar a câmera. Enquadrar mapa retorna à mesa.</p>${c('sky-topColor', 'Cor do céu', sky.topColor)}${c('sky-horizonColor', 'Cor do horizonte', sky.horizonColor)}${c('background', 'Fundo sem céu', look.background)}
    ${details('sky-celestial', 'Sol, lua e estrelas', `${b('sky-celestialEnabled', 'Mostrar sol / lua', sky.celestialEnabled)}${n('sky-discSize', 'Tamanho aparente do sol / lua', sky.discSize, { min: .005, max: .15, step: .005 })}${b('sky-stars', 'Estrelas à noite', sky.stars)}`)}
    ${details('sky-clouds', 'Nuvens', `${b('sky-clouds', 'Mostrar nuvens', sky.clouds)}${c('sky-cloudColor', 'Cor das nuvens', sky.cloudColor)}${n('sky-cloudCoverage', 'Cobertura', sky.cloudCoverage, { min: 0, max: 1 })}${n('sky-cloudOpacity', 'Opacidade', sky.cloudOpacity, { min: 0, max: 1 })}${n('sky-cloudSpeed', 'Velocidade das nuvens', sky.cloudSpeed, { min: 0, max: 1, step: .005 })}${n('sky-cloudScale', 'Escala do padrão', sky.cloudScale, { min: .1, max: 20 })}${n('sky-seed', 'Seed do céu', sky.seed, { min: 0, max: 2147483647, step: 1 })}`)}
  </section>
  <section><span class="eyebrow">CLIMA E PARTÍCULAS</span><label class="field"><span>Efeito na região</span><select data-field="weather-type">${[['none','Sem partículas'],['rain','Chuva'],['dust','Poeira suspensa'],['embers','Brasas'],['smoke','Fumaça suave']].map(([v,l]) => `<option value="${v}" ${weather.type === v ? 'selected' : ''}>${l}</option>`).join('')}</select></label>
    ${weather.type !== 'none' ? `${n('weather-count', 'Quantidade de partículas', weather.count, { min: 0, max: 3000, step: 50 })}${c('weather-color', 'Cor das partículas', weather.color)}${n('weather-opacity', 'Opacidade', weather.opacity, { min: 0, max: 1 })}${n('weather-speed', 'Velocidade · m/s', weather.speed, { min: 0, max: 100 })}${n('weather-particleSize', 'Tamanho · m', weather.particleSize, { min: .005, max: 3, step: .01 })}${details('weather-region', 'Região, vento e seed', `<span class="section-caption">CENTRO X/Z E ALTURA BASE · m</span><div class="axis-fields">${weather.center.map((v,i) => n(`weather-center-${i}`, ['X','Base Y','Z'][i], v)).join('')}</div><span class="section-caption">TAMANHO DA REGIÃO · m</span><div class="axis-fields">${weather.size.map((v,i) => n(`weather-size-${i}`, ['Largura','Altura','Profundidade'][i], v, { min: .1, max: 1000 })).join('')}</div><div class="field-grid">${weather.wind.map((v,i) => n(`weather-wind-${i}`, ['Vento X · m/s','Vento Z · m/s'][i], v, { min: -50, max: 50 })).join('')}</div>${n('weather-seed', 'Seed das partículas', weather.seed, { min: 0, max: 2147483647, step: 1 })}`)}<p class="microcopy">O efeito ocupa a região escolhida. Posicione chuva em áreas externas; teto e paredes não simulam colisão de partículas.</p>` : ''}
  </section>
  <section><span class="eyebrow">OBJETOS QUE ACENDEM À NOITE</span>${b('nightWindows-enabled', 'Acender janelas de vidro à noite', windows.enabled)}${c('nightWindows-color', 'Cor das janelas acesas', windows.color)}${n('nightWindows-intensity', 'Brilho das janelas', windows.intensity, { min: 0, max: 20 })}<p class="microcopy">Para um prédio importado, selecione o objeto e escolha o material das janelas em “Reagir ao horário”. Luzes podem ligar só de dia ou à noite. Materiais emissivos não iluminam os arredores sozinhos.</p></section>`;
}

export function bindingPanel(record, look, slots, open, { numberField: n, colorField: c, checkField: b }) {
  const binding = { ...BINDING_DEFAULTS, ...look.environmentBindings?.[record.id] }, exists = Boolean(look.environmentBindings?.[record.id]), light = Boolean(record.type);
  return `<section><details data-atmosphere-section="binding" ${open.has('binding') ? 'open' : ''}><summary>Reagir ao horário · dia / noite</summary>
    ${b('binding-enabled', light ? 'Ligar esta luz conforme o horário' : 'Acender material conforme o horário', exists ? binding.enabled : false)}
    <label class="field"><span>Ativar em</span><select data-field="binding-phase">${[['night','Noite'],['day','Dia e tarde'],['always','Todos os horários']].map(([v,l]) => `<option value="${v}" ${binding.phase === v ? 'selected' : ''}>${l}</option>`).join('')}</select></label>
    ${light ? '' : `<label class="field"><span>Material que acende</span><select data-field="binding-slot"><option value="base">${record.kind === 'window' ? 'Vidro da janela' : 'Todos os materiais'}</option>${slots.filter(s => s !== 'base').map(s => `<option value="${esc(s)}" ${binding.slot === s ? 'selected' : ''}>${esc(s)}</option>`).join('')}${binding.slot !== 'base' && !slots.includes(binding.slot) ? `<option selected value="${esc(binding.slot)}">${esc(binding.slot)} · material ausente</option>` : ''}</select></label>${c('binding-color', 'Cor quando aceso', binding.color)}${n('binding-intensity', 'Brilho emissivo', binding.intensity, { min: 0, max: 20 })}`}
    <button data-action="environment-binding-remove" ${exists ? '' : 'disabled'}>Remover vínculo individual</button><p class="microcopy">${light ? 'A intensidade e a cor continuam nos controles da luz. O vínculo escolhe quando ela liga.' : 'O efeito altera apenas esta instância. Vidros seguem a regra global quando não há vínculo individual.'}</p></details></section>`;
}
