import { VEGETATION_ASSETS, WATER_RANGES } from '../domain/landscape.js';
import { escapeHTML as esc } from './icons.js';
export function landscapePanel(document,options,catalog,{numberField}) {
  const terrains=Object.values(document.layout.entities).filter(e=>e.kind==='terrain');
  return `<section><span class="eyebrow">ÁGUA E VEGETAÇÃO</span><button data-action="terrain-water-brush" class="wide primary">Pintar água e escavar leito</button><div class="construction-grid"><button data-action="water-add">Criar água</button><button data-action="water-draw">Desenhar rio / lago</button></div><p class="microcopy">A superfície começa na altura de construção. Desenhe seu contorno, depois ajuste ondas, transparência ou congele no inspetor. O gelo oferece apoio para tokens.</p><span class="eyebrow">DISTRIBUIR VEGETAÇÃO</span><label class="field"><span>Terreno</span><select data-field="vegetation-terrainId"><option value="">Selecione um terreno</option>${terrains.map(t=>`<option value="${t.id}" ${options.terrainId===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label class="field"><span>Planta</span><select data-field="vegetation-assetId">${VEGETATION_ASSETS.map(id=>`<option value="${id}" ${options.assetId===id?'selected':''}>${esc(catalog.find(a=>a.id===id)?.name??id)}</option>`).join('')}</select></label>${numberField('vegetation-count','Quantidade desejada',options.count,{min:1,max:128,step:1})}${numberField('vegetation-seed','Variação da distribuição',options.seed,{min:0,max:65535,step:1})}<div class="field-grid">${numberField('vegetation-scaleMin','Escala mínima',options.scaleMin,{min:.1,max:5,step:.1})}${numberField('vegetation-scaleMax','Escala máxima',options.scaleMax,{min:.1,max:5,step:.1})}</div>${numberField('vegetation-slopeMax','Inclinação máxima · graus',options.slopeMax,{min:0,max:70,step:1})}<button data-action="vegetation-preview" class="wide" ${options.terrainId?'':'disabled'}>Prévia da vegetação</button><p class="microcopy">Evita água, pisos e objetos existentes. Revise e aceite a prévia; depois cada planta pode ser movida, texturizada ou receber neve. Ruínas, arcos, telhado e passarela ficam em Assets; filtre por Montanha.</p></section>`;
}
export function waterPanel(record,{numberField,colorField},document) {
  const w=record.water, ice=w.state==='ice';
  const terrains=Object.values(document?.layout.entities??{}).filter(e=>e.kind==='terrain');
  const labels={opacity:'Transparência · opacidade 0–1',waveHeight:'Altura das ondas · m',waveScale:'Comprimento das ondas · m',speed:'Velocidade da água',direction:'Direção do fluxo · graus'};
  return `<section><span class="eyebrow">ÁGUA / GELO</span><label class="field"><span>Estado da superfície</span><select data-field="water-state"><option value="water" ${!ice?'selected':''}>Água líquida</option><option value="ice" ${ice?'selected':''}>Gelo sólido</option></select></label><div class="field-grid">${numberField('width','Largura · m',record.width,{min:.1})}${numberField('length','Comprimento · m',record.length,{min:.1})}</div>${numberField('depth',ice?'Espessura do gelo · m':'Profundidade de referência · m',record.depth,{min:.02,max:20})}${!ice?colorField('material-color','Cor da água',record.material.color)+Object.entries(WATER_RANGES).map(([key,[min,max]])=>numberField(`water-${key}`,labels[key],w[key],{min,max,step:key==='direction'?5:.05})).join(''):''}${terrains.length?`<div class=water-bed-controls><label class=field><span>Terreno do leito</span><select data-water-terrain>${terrains.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></label><button data-action="water-bed-preview" class="wide">Prévia · rebaixar leito sob esta água</button><p class=microcopy>Use depois de mudar nível, ondas ou contorno. Rebaixa o terreno com margem; preserva a água e permite desfazer. Evita interseção com relevo e neve.</p></div>`:''}<p class="microcopy">${ice?'O topo do gelo fica na altura Y; a espessura cresce para baixo. Recebe textura de fissuras e neve. Para descongelar, desvincule primeiro os elementos apoiados neste gelo.':'Ondas e brilho animados; Pausar efeitos e movimento reduzido param a animação. A profundidade escurece a cor e não cria um fundo sólido. Água não serve de apoio; escolha um terreno/piso para os tokens.'}</p></section>`;
}
